# Generated by Django 5.1.3 on 2024-11-29 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0004_alter_standard_upload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to='standard/'),
        ),
    ]
