# Generated by Django 5.1.3 on 2024-11-29 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0006_inspectionrequirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodicTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('time_period', models.CharField(choices=[('35d', 'Every 35 Days'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=50)),
                ('specification', models.TextField()),
                ('number_of_specimens', models.PositiveIntegerField()),
                ('material', models.CharField(max_length=255)),
                ('dimensions', models.CharField(max_length=255)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodic_tests', to='standard.standard')),
            ],
        ),
    ]
