# Generated by Django 5.1.3 on 2025-04-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capability',
            name='cost_usd',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Standard market pricing', max_digits=10),
            preserve_default=False,
        ),
    ]
