# Generated by Django 5.1.3 on 2025-04-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0002_capability_cost_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='capability',
            name='env_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='capability',
            name='material_surcharge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='capability',
            name='post_process_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='capability',
            name='setup_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='capability',
            name='size_adjustment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='capability',
            name='testing_cert_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='capability',
            name='cost_usd',
            field=models.DecimalField(decimal_places=2, help_text='Total estimated cost', max_digits=10),
        ),
    ]
