# Generated by Django 5.1.3 on 2025-04-17 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0003_capability_env_fee_capability_material_surcharge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capability',
            name='base_job_setup_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='capability',
            name='complex_part_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='capability',
            name='min_per_part_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='capability',
            name='optional_addons',
            field=models.TextField(blank=True, help_text='Optional services or notes (e.g. expedited service, part marking)'),
        ),
        migrations.AddField(
            model_name='capability',
            name='simple_part_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='capability',
            name='cost_usd',
            field=models.DecimalField(decimal_places=2, help_text='Base process rate', max_digits=10),
        ),
    ]
