# Generated by Django 5.1.3 on 2025-04-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0005_addon_remove_capability_optional_addons_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOnTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='addon',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='addons', to='landing_page.addontag'),
        ),
    ]
