# Generated by Django 5.1.3 on 2025-04-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0006_addontag_addon_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapabilityTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='capability',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='capabilities', to='landing_page.capabilitytag'),
        ),
    ]
