# Generated by Django 5.1.3 on 2025-03-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0004_alter_processstep_step_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='process',
            options={'verbose_name': 'Process', 'verbose_name_plural': 'Processes'},
        ),
        migrations.AlterModelOptions(
            name='processstep',
            options={'ordering': ['step_number'], 'verbose_name': 'Process Step', 'verbose_name_plural': 'Process Steps'},
        ),
        migrations.AlterUniqueTogether(
            name='process',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='process',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
