# Generated by Django 5.1.3 on 2025-03-31 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0010_standard_previous_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionrequirement',
            name='date',
            field=models.DateField(blank=True, help_text='Date the inspection was performed', null=True),
        ),
        migrations.AddField(
            model_name='inspectionrequirement',
            name='operator',
            field=models.CharField(blank=True, help_text='Operator who performed the inspection', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inspectionrequirement',
            name='paragraph_section',
            field=models.CharField(blank=True, help_text='Section in the standard where this inspection is referenced', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inspectionrequirement',
            name='sampling_plan',
            field=models.CharField(blank=True, help_text='Sampling plan details', max_length=255, null=True),
        ),
    ]
