# Generated by Django 5.1.3 on 2025-04-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0011_inspectionrequirement_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='standard',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='standard',
            name='process',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='classification',
            name='class_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classification',
            name='class_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='classification',
            name='method',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='classification',
            name='method_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classification',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='classification',
            name='type_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspectionrequirement',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspectionrequirement',
            name='operator',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inspectionrequirement',
            name='paragraph_section',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inspectionrequirement',
            name='sampling_plan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='periodictest',
            name='specification',
            field=models.TextField(),
        ),
    ]
