# Generated by Django 5.1.3 on 2025-04-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0012_alter_standard_options_standard_process_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard',
            name='process',
            field=models.CharField(choices=[('anodize', 'Anodizing'), ('brush plate', 'Brush Plate'), ('clean', 'Cleaning'), ('conversion coating', 'Conversion Coating'), ('electroplate', 'Electroplate'), ('nital etch', 'Nital Etch'), ('paint', 'Paint'), ('passivation', 'Passivation'), ('pre-pen etch', 'Pre-Pen Etch'), ('strip', 'Stripping of Coating')], default=2, max_length=50),
            preserve_default=False,
        ),
    ]
