# Generated by Django 5.1.3 on 2025-04-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0013_alter_standard_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard',
            name='process',
            field=models.CharField(choices=[('anodize', 'Anodizing'), ('brush plate', 'Brush Plating'), ('clean', 'Cleaning'), ('conversion coating', 'Conversion Coating'), ('electroplate', 'Electroplating'), ('nital etch', 'Nital Etch'), ('paint', 'Paint'), ('passivation', 'Passivation'), ('pre-pen etch', 'Pre-Pen Etch'), ('strip', 'Stripping of Coating')], max_length=50),
        ),
    ]
