# Generated by Django 5.1.3 on 2025-06-20 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0015_standard_nadcap_alter_standard_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='classification',
            name='plate_asf',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Plating ASF (Amps per Square Foot)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='classification',
            name='plating_time_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Plating Time in Mintutes', null=True),
        ),
        migrations.AddField(
            model_name='classification',
            name='strike_asf',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Strike ASF (Amps per Square Foot)', max_digits=6, null=True),
        ),
    ]
