# Generated by Django 5.1.3 on 2025-08-18 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0016_classification_plate_asf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodicTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_on', models.DateField(auto_now_add=True)),
                ('performed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('passed', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='standard.periodictest')),
            ],
            options={
                'ordering': ['-performed_on'],
            },
        ),
    ]
