# Generated by Django 5.1.3 on 2025-08-22 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0017_periodictestresult'),
        ('tank_controls', '0002_alter_checkspec_options_alter_chemicalspec_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspectionrequirement',
            options={'ordering': ['standard__name', 'name']},
        ),
        migrations.CreateModel(
            name='StandardPeriodicRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodic_requirements', to='standard.standard')),
                ('test_spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standard_links', to='tank_controls.periodictestspec')),
            ],
            options={
                'ordering': ['standard__name', 'test_spec__name'],
                'unique_together': {('standard', 'test_spec')},
            },
        ),
    ]
