# Generated by Django 5.2 on 2025-10-28 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0018_alter_inspectionrequirement_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='plating_time_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Plating Time in Minutes', null=True),
        ),
        migrations.AlterField(
            model_name='periodictest',
            name='specification',
            field=models.TextField(help_text='Spec paragraph, method, acceptance criteria, etc.'),
        ),
        migrations.AlterField(
            model_name='standardperiodicrequirement',
            name='notes',
            field=models.TextField(blank=True, help_text='Any tailoring for this standard (panel alloy, thickness, etc.).', null=True),
        ),
        migrations.CreateModel(
            name='StandardProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_type', models.CharField(choices=[('anodize', 'Anodizing'), ('brush plate', 'Brush Plating'), ('clean', 'Cleaning'), ('conversion coating', 'Conversion Coating'), ('electroplate', 'Electroplating'), ('nital etch', 'Nital Etch'), ('paint', 'Paint'), ('passivation', 'Passivation'), ('pre-pen etch', 'Pre-Pen Etch'), ('strip', 'Stripping of Coating'), ('thermal', 'Thermal Treatment')], help_text='Which kind of process this represents (clean, plate, strip, etc.).', max_length=50)),
                ('title', models.CharField(help_text="Friendly label for operators, e.g. 'Alkaline Clean', 'Cadmium Plate', 'Nickel Strip'.", max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Local instructions / limits that apply to this block of the spec only.', null=True)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standard_processes', to='standard.standard')),
            ],
            options={
                'ordering': ['standard__name', 'title'],
                'unique_together': {('standard', 'title')},
            },
        ),
        migrations.AddField(
            model_name='classification',
            name='standard_process',
            field=models.ForeignKey(blank=True, help_text='If set: this classification only applies to that sub-process.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classifications', to='standard.standardprocess'),
        ),
        migrations.AddField(
            model_name='inspectionrequirement',
            name='standard_process',
            field=models.ForeignKey(blank=True, help_text='If set: only applies to this sub-process. If blank: applies to the whole standard.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='standard.standardprocess'),
        ),
    ]
