# Generated by Django 5.2 on 2025-11-25 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0019_alter_classification_plating_time_minutes_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='standard',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='classification',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='standard.standard'),
        ),
        migrations.AddConstraint(
            model_name='standard',
            constraint=models.UniqueConstraint(fields=('name', 'revision'), name='unique_standard_name_revision'),
        ),
        migrations.RemoveField(
            model_name='standard',
            name='process',
        ),
    ]
