# Generated by Django 5.2 on 2025-11-25 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0020_alter_standard_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='standard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='standard.standard'),
        ),
    ]
