# Generated by Django 5.2 on 2025-12-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0021_alter_classification_standard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardprocess',
            name='process_type',
            field=models.CharField(choices=[('anodize', 'Anodizing'), ('brush plate', 'Brush Plating'), ('clean', 'Cleaning'), ('codes', 'Process Codes'), ('conversion coating', 'Conversion Coating'), ('electroplate', 'Electroplating'), ('index', 'Index of Specifications'), ('nital etch', 'Nital Etch'), ('paint', 'Paint'), ('passivation', 'Passivation'), ('pre-pen etch', 'Pre-Pen Etch'), ('strip', 'Stripping of Coating'), ('thermal', 'Thermal Treatment')], help_text='Which kind of process this represents (clean, plate, strip, etc.).', max_length=50),
        ),
    ]
