# Generated by Django 5.2 on 2026-03-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0022_alter_standardprocess_process_type'),
        ('tank_controls', '0002_alter_checkspec_options_alter_chemicalspec_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='standardperiodicrequirement',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='standardprocess',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='standardperiodicrequirement',
            constraint=models.UniqueConstraint(fields=('standard', 'test_spec'), name='unique_standard_periodic_requirement'),
        ),
        migrations.AddConstraint(
            model_name='standardprocess',
            constraint=models.UniqueConstraint(fields=('standard', 'title'), name='unique_standard_process_title'),
        ),
    ]
