services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/postgres_data
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
      - POSTGRES_PORT=5432
    ports:
      - 5432:5432
  pgadmin:
    image: "elestio/pgadmin:REL-8_13"
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: "email@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5050:80"

volumes:
  postgres_data: