# Generated by Django 5.1.3 on 2025-03-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Fixture Name', max_length=255, unique=True)),
                ('max_amps', models.PositiveIntegerField(help_text='Max Amps the fixture can handle')),
                ('drawing', models.FileField(blank=True, help_text='Upload fixture drawing', null=True, upload_to='fixture_drawings/')),
                ('quantity_available', models.PositiveIntegerField(default=0, help_text='Number of fixtures available')),
                ('fixtures_due_for_repair', models.PositiveIntegerField(default=0, help_text='Number of fixtures currently needing repair')),
                ('inspection_schedule', models.DateField(help_text='Next scheduled inspection date')),
                ('last_inspection_date', models.DateField(blank=True, help_text='Last completed inspection', null=True)),
                ('repair_notes', models.TextField(blank=True, help_text='Details of repairs needed/completed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
