# Generated by Django 5.1.3 on 2025-03-28 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PMTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('frequency_days', models.IntegerField(help_text='Frequency in days')),
            ],
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rack_id', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('coating_type', models.CharField(blank=True, max_length=100)),
                ('in_service_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RackPM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_performed', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('passed', models.BooleanField(default=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pm_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fixtures.pmtask')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fixtures.rack')),
            ],
        ),
        migrations.DeleteModel(
            name='Fixture',
        ),
    ]
