# Generated by Django 5.1.3 on 2025-04-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0004_tank_created_at_tank_updated_at_alter_tank_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionline',
            name='name',
            field=models.CharField(choices=[('l1', 'Line 1'), ('l2', 'Line 2'), ('l3', 'Line 3'), ('l4', 'Line 4'), ('l5', 'Line 5'), ('l6', 'Line 6'), ('l7', 'Line 7'), ('kl', 'Kernersville'), ('hw', 'Honeywell')], help_text='Select the production line', max_length=5, unique=True),
        ),
    ]
