# Generated by Django 5.1.3 on 2024-12-02 02:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0003_partdetails_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='job_identity',
            field=models.CharField(choices=[('chrome_plate', 'Chrome Plate'), ('cadmium_plate', 'Cadmium Plate'), ('etch', 'Etch'), ('anodize', 'Anodize'), ('paint', 'Paint')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
