# Generated by Django 5.1.3 on 2025-03-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0020_alter_partdetails_job_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='job_identity',
            field=models.CharField(choices=[('alkaline clean', 'Alkaline Clean'), ('anodize', 'Anodize'), ('cadmium_plate', 'Cadmium Plate'), ('chemical conversion', 'Chemical Conversion'), ('chrome_plate', 'Chrome Plate'), ('cleaning', 'Cleaning'), ('Descale', 'Descale'), ('etch', 'Etch'), ('ni_plate', 'Nickel Plate'), ('paint', 'Paint'), ('passivation', 'Passivation'), ('solvent_clean', 'Solvent Clean')], max_length=50),
        ),
        migrations.AlterField(
            model_name='partdetails',
            name='job_identity',
            field=models.CharField(choices=[('alkaline clean', 'Alkaline Clean'), ('anodize', 'Anodize'), ('brush_plate', 'Brush Plate'), ('cadmium_plate', 'Cadmium Plate'), ('chrome_plate', 'Chrome Plate'), ('cleaning', 'Cleaning'), ('conversion_coating', 'Conversion Coating'), ('Descale', 'Descale'), ('etch', 'Etch'), ('ni_plate', 'Nickel Plate'), ('nital_temper_etch', 'Nital/Temper Etch'), ('paint', 'Paint'), ('passivation', 'Passivation'), ('pre_pen_etch', 'Pre-Penetrant Etching'), ('solvent_clean', 'Solvent Clean'), ('stripping', 'Stripping')], max_length=50),
        ),
    ]
