# Generated by Django 5.1.3 on 2025-03-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0021_alter_jobdetails_job_identity_and_more'),
        ('standard', '0010_standard_previous_version_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobdetails',
            options={'ordering': ['job_number'], 'verbose_name': 'Job Detail', 'verbose_name_plural': 'Job Details'},
        ),
        migrations.AlterModelOptions(
            name='part',
            options={'verbose_name': 'Part', 'verbose_name_plural': 'Parts'},
        ),
        migrations.AlterModelOptions(
            name='partdetails',
            options={'ordering': ['job_identity'], 'verbose_name': 'Part Detail', 'verbose_name_plural': 'Part Details'},
        ),
        migrations.AlterUniqueTogether(
            name='jobdetails',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='partdetails',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='current_density',
            field=models.FloatField(blank=True, null=True, verbose_name='Current Density (amps/sq in)'),
        ),
        migrations.AddConstraint(
            model_name='jobdetails',
            constraint=models.UniqueConstraint(fields=('part_detail', 'job_number', 'job_identity', 'surface_repaired', 'processing_standard', 'classification'), name='unique_job_details'),
        ),
        migrations.AddConstraint(
            model_name='partdetails',
            constraint=models.UniqueConstraint(fields=('part', 'job_identity', 'processing_standard', 'classification'), name='unique_part_job_standard_classification'),
        ),
    ]
