# Generated by Django 5.1.3 on 2025-03-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0023_remove_partdetails_classification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(default='CPTS', max_length=255)),
                ('revision', models.CharField(default='0', max_length=50)),
                ('date', models.DateField()),
                ('repair_station', models.CharField(default='QKPR504X', max_length=255)),
                ('footer_text', models.TextField(blank=True, help_text='Additional footer content')),
            ],
        ),
    ]
