# Generated by Django 5.1.3 on 2024-12-02 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0002_alter_jobdetails_options_alter_partdetails_options'),
        ('standard', '0008_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='partdetails',
            name='classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='standard.classification'),
        ),
    ]
