# Generated by Django 5.1.3 on 2024-12-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0006_alter_partdetails_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='customer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
