# Generated by Django 5.1.3 on 2024-12-17 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0010_jobdetails_surface_area'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobdetails',
            unique_together={('part_detail', 'job_identity', 'surface_repaired')},
        ),
    ]
