# Generated by Django 5.1.3 on 2025-03-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0019_alter_jobdetails_current_density_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partdetails',
            name='job_identity',
            field=models.CharField(choices=[('chrome_plate', 'Chrome Plate'), ('cadmium_plate', 'Cadmium Plate'), ('etch', 'Etch'), ('anodize', 'Anodize'), ('paint', 'Paint'), ('passivation', 'Passivation'), ('cleaning', 'cleaning'), ('chemical conversion', 'chemical conversion'), ('descale', 'descale')], max_length=50),
        ),
    ]
