# Generated by Django 5.1.3 on 2025-03-13 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0022_alter_jobdetails_options_alter_part_options_and_more'),
        ('standard', '0010_standard_previous_version_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partdetails',
            name='classification',
        ),
        migrations.RemoveField(
            model_name='partdetails',
            name='part',
        ),
        migrations.RemoveField(
            model_name='partdetails',
            name='processing_standard',
        ),
        migrations.CreateModel(
            name='PartStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part_standards', to='standard.classification')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standards', to='part.part')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_standards', to='standard.standard')),
            ],
            options={
                'verbose_name': 'Part Standard',
                'verbose_name_plural': 'Part Standards',
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_order_number', models.CharField(max_length=255)),
                ('surface_repaired', models.CharField(blank=True, max_length=255, null=True)),
                ('customer', models.CharField(blank=True, max_length=50, null=True)),
                ('purchase_order_with_revision', models.CharField(blank=True, max_length=255, null=True)),
                ('part_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('serial_or_lot_numbers', models.TextField(blank=True, null=True)),
                ('surface_area', models.FloatField(blank=True, null=True, verbose_name='Surface Area (sq in)')),
                ('date', models.DateField(blank=True, null=True)),
                ('current_density', models.FloatField(blank=True, null=True, verbose_name='Current Density (amps/sq in)')),
                ('amps', models.FloatField(blank=True, null=True, verbose_name='Amps Required')),
                ('job_identity', models.CharField(choices=[('alkaline clean', 'Alkaline Clean'), ('anodize', 'Anodize'), ('cadmium_plate', 'Cadmium Plate'), ('chemical conversion', 'Chemical Conversion'), ('chrome_plate', 'Chrome Plate'), ('cleaning', 'Cleaning'), ('Descale', 'Descale'), ('etch', 'Etch'), ('ni_plate', 'Nickel Plate'), ('paint', 'Paint'), ('passivation', 'Passivation'), ('solvent_clean', 'Solvent Clean')], max_length=50)),
                ('classification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='standard.classification')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='part.part')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='standard.standard')),
            ],
            options={
                'verbose_name': 'Work Order',
                'verbose_name_plural': 'Work Orders',
                'ordering': ['work_order_number'],
            },
        ),
        migrations.DeleteModel(
            name='JobDetails',
        ),
        migrations.DeleteModel(
            name='PartDetails',
        ),
        migrations.AddConstraint(
            model_name='partstandard',
            constraint=models.UniqueConstraint(fields=('part', 'standard', 'classification'), name='unique_part_standard_classification'),
        ),
        migrations.AddConstraint(
            model_name='workorder',
            constraint=models.UniqueConstraint(fields=('part', 'work_order_number', 'standard', 'classification', 'surface_repaired'), name='unique_work_order_details'),
        ),
    ]
