# Generated by Django 5.1.3 on 2025-03-28 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0002_pmtask_rack_rackpm_delete_fixture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmtask',
            name='description',
            field=models.TextField(help_text='Detailed description of the PM task, including what to check and how'),
        ),
        migrations.AlterField(
            model_name='pmtask',
            name='frequency_days',
            field=models.IntegerField(help_text='How often this task should be performed (e.g. every 30 days)'),
        ),
        migrations.AlterField(
            model_name='pmtask',
            name='title',
            field=models.CharField(help_text='Short name of the preventive maintenance task (e.g. Visual Inspection)', max_length=100),
        ),
        migrations.AlterField(
            model_name='rack',
            name='coating_type',
            field=models.CharField(blank=True, help_text='Type of rack coating (e.g. plastisol, PVC, Teflon)', max_length=100),
        ),
        migrations.AlterField(
            model_name='rack',
            name='description',
            field=models.TextField(blank=True, help_text='Short description of the rack, including type or purpose'),
        ),
        migrations.AlterField(
            model_name='rack',
            name='in_service_date',
            field=models.DateField(blank=True, help_text='Date the rack was first put into use', null=True),
        ),
        migrations.AlterField(
            model_name='rack',
            name='location',
            field=models.CharField(blank=True, help_text='Where the rack is normally stored or used', max_length=100),
        ),
        migrations.AlterField(
            model_name='rack',
            name='rack_id',
            field=models.CharField(help_text='Unique ID or tag number of the rack (e.g. R-101)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='rackpm',
            name='date_performed',
            field=models.DateField(auto_now_add=True, help_text='Date the PM task was performed (automatically added)'),
        ),
        migrations.AlterField(
            model_name='rackpm',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional notes about what was found or done during the PM'),
        ),
        migrations.AlterField(
            model_name='rackpm',
            name='passed',
            field=models.BooleanField(default=True, help_text='Check if the rack passed the inspection or PM'),
        ),
        migrations.AlterField(
            model_name='rackpm',
            name='performed_by',
            field=models.ForeignKey(help_text='User who performed the task', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rackpm',
            name='pm_task',
            field=models.ForeignKey(help_text='The PM task that was performed', on_delete=django.db.models.deletion.CASCADE, to='fixtures.pmtask'),
        ),
        migrations.AlterField(
            model_name='rackpm',
            name='rack',
            field=models.ForeignKey(help_text='The rack that was inspected or maintained', on_delete=django.db.models.deletion.CASCADE, to='fixtures.rack'),
        ),
    ]
