# Generated by Django 5.1.3 on 2025-03-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0003_alter_pmtask_description_alter_pmtask_frequency_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rack',
            name='photo',
            field=models.ImageField(blank=True, help_text='Optional image of the rack', null=True, upload_to='rack_photos/'),
        ),
        migrations.AddField(
            model_name='rackpm',
            name='photo',
            field=models.ImageField(blank=True, help_text='Optional photo taken during or after the PM', null=True, upload_to='pm_photos/'),
        ),
    ]
