# Generated by Django 5.1.3 on 2025-03-28 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0004_rack_photo_rackpm_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rack',
            name='photo',
        ),
        migrations.AddField(
            model_name='pmtask',
            name='instruction_photo',
            field=models.ImageField(blank=True, help_text='Optional photo showing how to perform this task', null=True, upload_to='task_photos/'),
        ),
        migrations.AlterField(
            model_name='pmtask',
            name='description',
            field=models.TextField(help_text='Detailed description of the PM task'),
        ),
        migrations.AlterField(
            model_name='pmtask',
            name='frequency_days',
            field=models.IntegerField(help_text='How often this task should be performed'),
        ),
        migrations.AlterField(
            model_name='pmtask',
            name='title',
            field=models.CharField(help_text='Short name of the preventive maintenance task', max_length=100),
        ),
        migrations.AlterField(
            model_name='rackpm',
            name='date_performed',
            field=models.DateField(auto_now_add=True, help_text='Date the PM task was performed'),
        ),
        migrations.AlterField(
            model_name='rackpm',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional notes about the PM'),
        ),
        migrations.AlterField(
            model_name='rackpm',
            name='passed',
            field=models.BooleanField(default=True, help_text='Check if the rack passed the PM'),
        ),
        migrations.CreateModel(
            name='RackPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload a photo of the rack', upload_to='rack_photos/')),
                ('rack', models.ForeignKey(help_text='The rack this photo is associated with', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='fixtures.rack')),
            ],
        ),
    ]
