# Generated by Django 5.1.3 on 2025-03-28 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0005_remove_rack_photo_pmtask_instruction_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RackPMPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_every_days', models.IntegerField(blank=True, help_text='Override task frequency if needed', null=True)),
                ('rack', models.ForeignKey(help_text='The rack this PM plan applies to', on_delete=django.db.models.deletion.CASCADE, related_name='pm_plan', to='fixtures.rack')),
                ('task', models.ForeignKey(help_text='The task this rack needs to follow', on_delete=django.db.models.deletion.CASCADE, to='fixtures.pmtask')),
            ],
        ),
    ]
