# Generated by Django 5.1.3 on 2025-03-28 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0006_rackpmplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='rackpmplan',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional notes specific to this rack-task pairing'),
        ),
        migrations.AlterField(
            model_name='rackpmplan',
            name='due_every_days',
            field=models.IntegerField(blank=True, help_text='Override default task frequency (optional)', null=True),
        ),
        migrations.AlterField(
            model_name='rackpmplan',
            name='rack',
            field=models.ForeignKey(help_text='The rack this planned PM applies to', on_delete=django.db.models.deletion.CASCADE, related_name='pm_plan', to='fixtures.rack'),
        ),
        migrations.AlterField(
            model_name='rackpmplan',
            name='task',
            field=models.ForeignKey(help_text='The preventive maintenance task to perform', on_delete=django.db.models.deletion.CASCADE, to='fixtures.pmtask'),
        ),
    ]
