# Generated by Django 5.1.3 on 2025-03-28 19:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0007_rackpmplan_notes_alter_rackpmplan_due_every_days_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rackpm',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Timestamp when this record was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rackpm',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who logged this PM task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rackpm_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rackpm',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified'),
        ),
        migrations.AddField(
            model_name='rackpm',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this PM task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rackpm_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rackpm',
            name='performed_by',
            field=models.ForeignKey(help_text='User who physically performed the PM task', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
