# Generated by Django 5.1.3 on 2025-03-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masking', '0005_alter_maskingprocess_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maskingprocess',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='maskingstep',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='maskingstep',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='step_images/'),
        ),
    ]
