# Generated by Django 5.1.3 on 2025-03-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemical',
            name='auto_reordered',
            field=models.BooleanField(default=False, help_text='Indicates if an auto-reorder has been triggered.'),
        ),
        migrations.AddField(
            model_name='chemical',
            name='coc_scan',
            field=models.FileField(blank=True, help_text='Upload CoC document', null=True, upload_to='coc_scans/'),
        ),
        migrations.AddField(
            model_name='chemical',
            name='max_stock',
            field=models.PositiveIntegerField(default=10, help_text='Maximum stock allowed.'),
        ),
        migrations.AddField(
            model_name='chemical',
            name='min_stock',
            field=models.PositiveIntegerField(default=1, help_text='Minimum stock before reorder is required.'),
        ),
        migrations.AddField(
            model_name='chemical',
            name='reorder_quantity',
            field=models.PositiveIntegerField(default=5, help_text='Quantity to reorder when below minimum.'),
        ),
        migrations.AlterField(
            model_name='chemical',
            name='lot_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='chemical',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='chemical',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
