# Generated by Django 5.1.3 on 2025-03-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0003_remove_chemical_auto_reordered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemical',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Date when the chemical expires (leave blank if N/A)', null=True),
        ),
    ]
