# Generated by Django 5.1.3 on 2025-02-24 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0008_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodictest',
            name='specification',
            field=models.TextField(help_text='Section and Description the test complies with'),
        ),
    ]
