# Generated by Django 5.2 on 2025-12-12 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('process', '0010_process_standard_process'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_order', models.CharField(max_length=100, unique=True)),
                ('part_number', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('planned_start_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('done', 'Done'), ('hold', 'On Hold')], default='planned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_orders', to='process.process')),
            ],
            options={
                'verbose_name': 'Manufacturing Order',
                'verbose_name_plural': 'Manufacturing Orders',
                'ordering': ['planned_start_time'],
            },
        ),
    ]
