# Generated by Django 5.2 on 2025-12-11 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('methods', '0034_method_run_time_max_method_run_time_min_and_more'),
        ('process', '0010_process_standard_process'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('resource_type', models.CharField(choices=[('tank', 'Tank'), ('oven', 'Oven'), ('line', 'Line'), ('operator', 'Operator'), ('cell', 'Work Cell')], max_length=20)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ManufacturingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_order', models.CharField(help_text='Manufacturing work order number', max_length=100, unique=True)),
                ('part_number', models.CharField(max_length=100)),
                ('part_description', models.CharField(blank=True, max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('estimated_finish_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('done', 'Done'), ('hold', 'On Hold'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('part_status', models.CharField(choices=[('not_received', 'Not Received'), ('received', 'Received'), ('not_booked', 'Not Booked'), ('booked', 'Booked')], default='not_received', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Primary operator / owner', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manufacturing_orders', to=settings.AUTH_USER_MODEL)),
                ('process', models.ForeignKey(help_text='Process routing to use for this work order', on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_orders', to='process.process')),
            ],
            options={
                'ordering': ['due_date', 'work_order'],
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(help_text='Order of this operation within the routing')),
                ('planned_start', models.DateTimeField()),
                ('planned_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('hold', 'On Hold'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('manufacturing_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='scheduler.manufacturingorder')),
                ('method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='methods.method')),
                ('process_step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='process.processstep')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='scheduler.resource')),
            ],
            options={
                'ordering': ['manufacturing_order', 'sequence'],
                'unique_together': {('manufacturing_order', 'sequence')},
            },
        ),
    ]
