# Generated by Django 5.2 on 2025-12-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_delaylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturingorder',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
