# Generated by Django 5.2 on 2025-12-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0010_process_standard_process'),
        ('scheduler', '0003_manufacturingorder_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturingorder',
            name='occurrence',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='manufacturingorder',
            name='work_order',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='manufacturingorder',
            constraint=models.UniqueConstraint(fields=('work_order', 'occurrence'), name='uq_work_order_occurrence'),
        ),
    ]
