# Generated by Django 5.2 on 2025-12-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0010_process_standard_process'),
        ('scheduler', '0004_manufacturingorder_occurrence_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delaylog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='delaylog',
            name='added_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='manufacturingorder',
            index=models.Index(fields=['work_order', 'occurrence'], name='scheduler_m_work_or_496f84_idx'),
        ),
    ]
