# Generated by Django 5.1.3 on 2025-03-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionline',
            name='name',
            field=models.CharField(choices=[('l1', 'Line 1'), ('l2', 'Line 2'), ('l3', 'Line 3'), ('l4', 'Line 4'), ('l5', 'Line 5'), ('l6', 'Line 6'), ('l7', 'Line 7'), ('kl', 'Kernersville')], help_text='Production Line Name', max_length=5, unique=True),
        ),
    ]
