# Generated by Django 5.1.3 on 2024-12-02 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_processstep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processstep',
            name='step_number',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
