# Generated by Django 5.2 on 2026-01-08 13:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmulsifierProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('manufacturer', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['manufacturer', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ConcentrationCurve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('refractometer_id', models.CharField(blank=True, max_length=80)),
                ('water_source', models.CharField(blank=True, max_length=120)),
                ('temperature_note', models.CharField(blank=True, max_length=120)),
                ('target_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('low_limit_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('high_limit_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emulsifier_curves_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_active', '-created_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmulsifierProductLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(db_index=True, max_length=80)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('vendor', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='ndt.emulsifierproduct')),
            ],
            options={
                'ordering': ['-is_active', 'product__manufacturer', 'product__name', 'lot_number'],
            },
        ),
        migrations.CreateModel(
            name='EmulsifierMix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Example: 'PT Line Method D Mix - Jan 2026 - Batch 1'", max_length=160)),
                ('mixed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('target_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('curve_used', models.ForeignKey(blank=True, help_text='Optional: lock the intended curve for this mix (recommended).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mixes', to='ndt.concentrationcurve')),
                ('mixed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emulsifier_mixes', to=settings.AUTH_USER_MODEL)),
                ('product_lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mixes', to='ndt.emulsifierproductlot')),
            ],
            options={
                'ordering': ['-is_active', '-mixed_at', 'name'],
            },
        ),
        migrations.AddField(
            model_name='concentrationcurve',
            name='product_lot',
            field=models.ForeignKey(blank=True, help_text='Lot number used to build this calibration curve.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='curves', to='ndt.emulsifierproductlot'),
        ),
        migrations.CreateModel(
            name='WeeklyEmulsifierCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('refractometer_reading', models.DecimalField(decimal_places=3, max_digits=7)),
                ('calculated_concentration_percent', models.DecimalField(decimal_places=2, editable=False, max_digits=6)),
                ('in_limits', models.BooleanField(default=True, editable=False)),
                ('comments', models.TextField(blank=True)),
                ('curve_used', models.ForeignKey(help_text='Curve used for the calculation (captured for traceability).', on_delete=django.db.models.deletion.PROTECT, related_name='weekly_checks', to='ndt.concentrationcurve')),
                ('mix', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weekly_checks', to='ndt.emulsifiermix')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emulsifier_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='CurvePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading', models.DecimalField(decimal_places=3, max_digits=7)),
                ('concentration_percent', models.DecimalField(decimal_places=2, max_digits=6)),
                ('curve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curve_points', to='ndt.concentrationcurve')),
            ],
            options={
                'ordering': ['reading'],
                'constraints': [models.UniqueConstraint(fields=('curve', 'reading'), name='uniq_curve_reading')],
            },
        ),
        migrations.AddConstraint(
            model_name='emulsifierproductlot',
            constraint=models.UniqueConstraint(fields=('product', 'lot_number'), name='uniq_product_lot_number'),
        ),
        migrations.AddConstraint(
            model_name='weeklyemulsifiercheck',
            constraint=models.UniqueConstraint(fields=('mix', 'checked_at'), name='uniq_mix_checked_at'),
        ),
    ]
