# Generated by Django 5.1.3 on 2025-02-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0007_alter_method_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method',
            name='title',
            field=models.CharField(blank=True, choices=[('Pre-Cleaning', 'Pre-Cleaning'), ('Masking', 'Masking'), ('Racking', 'Racking'), ('Abrasive Blasting', 'Abrasive Blasting'), ('Cleaning', 'Cleaning'), ('Rinsing', 'Rinsing'), ('De-Oxidize/Pickle', 'De-Oxidize/Pickle'), ('Pre-Pen Etching', 'Pre-Pen Etching'), ('Electrolytic Clean', 'Electrolytic Clean'), ('Acid Desmut', 'Acid Desmut'), ('Etching', 'Etching'), ('Chemical Milling', 'Chemical Milling'), ('Conversion Coating', 'Conversion Coating'), ('Electroless Plating', 'Electroless Plating'), ('Anodize', 'Anodize'), ('Air Dry', 'Ary Dry'), ('Sealing', 'Sealing'), ('Barrel Plating', 'Barrel Plating'), ('Brush Plating', 'Brush Plating'), ('Electroplating', 'Electroplating'), ('Painting/Dry Film Coating', 'Painting/Dry Film Coating'), ('Thermal Treatment', 'Thermal Treatment'), ('Vacuum Cadmium & Aluminum IVD', 'Vacuum Cadmium & Aluminum IVD'), ('Stress Relief', 'Stress Relief'), ('Hydrogen Embrittlement Relief', 'Hydrogen Embrittlement Relief')], max_length=255),
        ),
    ]
