# Generated by Django 5.1.3 on 2025-06-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HazComSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=200)),
                ('section_description', models.TextField()),
            ],
        ),
    ]
