# Generated by Django 5.2 on 2025-11-18 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaskingProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=255)),
                ('masking_description', models.TextField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='masking.maskingprocess')),
            ],
            options={
                'verbose_name': 'Masking Process',
                'verbose_name_plural': 'Masking Processes',
                'ordering': ['part_number'],
                'unique_together': {('part_number', 'version')},
            },
        ),
        migrations.CreateModel(
            name='MaskingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='step_images/')),
                ('masking_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masking_steps', to='masking.maskingprocess')),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
    ]
