# Generated by Django 5.1.3 on 2024-12-03 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('part', '0007_jobdetails_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaskingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_revision', models.CharField(max_length=50)),
                ('masking_area', models.TextField()),
                ('masking_family', models.CharField(choices=[('tape', 'Tape'), ('wax', 'Wax'), ('lacquer', 'Lacquer')], max_length=50, verbose_name='Masking Family')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masking_profiles', to='part.part')),
            ],
        ),
        migrations.CreateModel(
            name='MaskingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_type', models.CharField(choices=[('front', 'Front'), ('top', 'Top'), ('right', 'Right'), ('closeup', 'Close-Up')], max_length=10)),
                ('image', models.ImageField(upload_to='masking_photos/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('masking_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='masking.maskingprofile')),
            ],
        ),
    ]
