# Generated by Django 5.1.3 on 2024-12-10 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('part', '0009_alter_part_part_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaskingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surface_repaired', models.TextField(blank=True, null=True, verbose_name='Surface Repaired')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('part_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masking_profiles', to='part.partdetails')),
            ],
        ),
    ]
