# Generated by Django 5.1.3 on 2024-12-05 15:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maskingprofile',
            name='job_identity',
            field=models.CharField(choices=[('chrome_plate', 'Chrome Plate'), ('cadmium_plate', 'Cadmium Plate'), ('etch', 'Etch'), ('anodize', 'Anodize'), ('paint', 'Paint')], default=django.utils.timezone.now, max_length=50, verbose_name='Job Identity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maskingprofile',
            name='surface_repaired',
            field=models.TextField(blank=True, null=True, verbose_name='Surface Repaired'),
        ),
    ]
