# Generated by Django 5.1.3 on 2024-12-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masking', '0002_maskingprofile_job_identity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maskingprofile',
            name='job_identity',
            field=models.CharField(choices=[('chrome_plate', 'Chrome Plate'), ('cadmium_plate', 'Cadmium Plate'), ('nickel plate', 'Nickel Plate'), ('etch', 'Etch'), ('anodize', 'Anodize'), ('paint', 'Paint'), ('chrome strip', 'Chrome Strip'), ('cad strip', 'Cad Strip'), ('nickel strip', 'Nickel Strip')], max_length=50, verbose_name='Job Identity'),
        ),
    ]
