# Generated by Django 5.1.3 on 2024-12-08 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masking', '0003_alter_maskingprofile_job_identity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maskingprofile',
            name='masking_area',
        ),
        migrations.RemoveField(
            model_name='maskingprofile',
            name='part_revision',
        ),
    ]
