# Generated by Django 5.1.3 on 2025-03-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masking', '0004_alter_maskingstep_masking_process_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maskingprocess',
            options={'ordering': ['part_number'], 'verbose_name': 'Masking Process', 'verbose_name_plural': 'Masking Processes'},
        ),
        migrations.AlterModelOptions(
            name='maskingstep',
            options={'ordering': ['step_number']},
        ),
        migrations.RenameField(
            model_name='maskingprocess',
            old_name='part_number_masking_description',
            new_name='masking_description',
        ),
        migrations.RenameField(
            model_name='maskingstep',
            old_name='masking_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='maskingstep',
            old_name='masking_step_number',
            new_name='step_number',
        ),
        migrations.RenameField(
            model_name='maskingstep',
            old_name='masking_repair_title',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='maskingstep',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='masking_steps/'),
        ),
        migrations.AlterUniqueTogether(
            name='maskingstep',
            unique_together={('masking_process', 'step_number')},
        ),
    ]
