# Generated by Django 5.1.3 on 2025-04-07 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masking', '0007_maskingprocess_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maskingprocess',
            options={'ordering': ['part_number'], 'verbose_name': 'Masking Process', 'verbose_name_plural': 'Masking Processes'},
        ),
    ]
