# Generated by Django 5.1.3 on 2024-12-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0007_jobdetails_customer'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='part',
            constraint=models.UniqueConstraint(fields=('part_number', 'part_revision'), name='unique_part_revision'),
        ),
    ]
