# Generated by Django 5.1.3 on 2024-12-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0014_alter_jobdetails_unique_together'),
        ('standard', '0008_classification'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobdetails',
            unique_together={('part_detail', 'job_number', 'job_identity', 'processing_standard', 'classification')},
        ),
        migrations.AddField(
            model_name='jobdetails',
            name='current_density',
            field=models.FloatField(blank=True, null=True, verbose_name='Current Density in square inches'),
        ),
    ]
