# Generated by Django 5.1.3 on 2024-12-18 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0016_alter_jobdetails_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='current_density',
            field=models.FloatField(blank=True, null=True, verbose_name='Current density in sq inches'),
        ),
    ]
