# Generated by Django 5.1.3 on 2024-12-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0017_jobdetails_current_density'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='current_density',
            field=models.FloatField(blank=True, null=True, verbose_name='Current density'),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='surface_area',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface Area'),
        ),
    ]
