# Generated by Django 5.1.3 on 2025-02-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0005_alter_parametertoberecorded_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method',
            name='title',
            field=models.CharField(blank=True, choices=[('Pre-Cleaning', 'Pre-Cleaning'), ('Masking', 'Masking'), ('Abrasive Blasting', 'Abrasive Blasting'), ('Cleaning', 'Cleaning'), ('Rinsing', 'Rinsing'), ('De-Oxidize/Pickle', 'De-Oxidize/Pickle'), ('Electrolytic Clean', 'Electrolytic Clean'), ('Acid Desmut', 'Acid Desmut'), ('Etching', 'Etching'), ('Chemical Milling', 'Chemical Milling'), ('Conversion Coating', 'Conversion Coating'), ('Electroless Plating', 'Electroless Plating'), ('Anodize', 'Anodize'), ('Sealing/Dying', 'Sealing/Dying'), ('Barrel Plating', 'Barrel Plating'), ('Brush Plating', 'Brush Plating'), ('Electroplating', 'Electroplating'), ('Painting/Dry Film Coating', 'Painting/Dry Film Coating'), ('Thermal Treatment', 'Thermal Treatment'), ('Vacuum Cadmium & Aluminum IVD', 'Vacuum Cadmium & Aluminum IVD')], max_length=255),
        ),
    ]
