# Generated by Django 5.1.3 on 2025-03-31 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0013_alter_method_title_alter_parametertoberecorded_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method',
            name='title',
            field=models.CharField(blank=True, help_text='Enter a custom title or select one below.', max_length=255),
        ),
    ]
