# Generated by Django 5.1.3 on 2025-04-07 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0014_alter_method_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='method',
            options={'ordering': ['title'], 'verbose_name': 'Method', 'verbose_name_plural': 'Methods'},
        ),
    ]
