# Generated by Django 5.1.3 on 2025-05-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0015_alter_method_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametertoberecorded',
            name='title',
            field=models.CharField(choices=[('Abrasive Blasting', 'Abrasive Blasting'), ('Acid Desmut', 'Acid Desmut'), ('Air Dry', 'Air Dry'), ('Alkaline Clean', 'Alkaline Clean'), ('Anodize', 'Anodize'), ('Barrel Plating', 'Barrel Plating'), ('Brush Plating', 'Brush Plating'), ('Cad Strip', 'Cad Strip'), ('Chemical Milling', 'Chemical Milling'), ('Cleaning', 'Cleaning'), ('Chrome Strip', 'Chrome Strip'), ('Conversion Coating', 'Conversion Coating'), ('De-Oxidize/Pickle', 'De-Oxidize/Pickle'), ('Demasking', 'Demasking'), ('Electroless Plating', 'Electroless Plating'), ('Electrolytic Clean', 'Electrolytic Clean'), ('Electroplating', 'Electroplating'), ('Etching', 'Etching'), ('FOD Inpsection', 'FOD Inspection'), ('Hydrogen Embrittlement Relief', 'Hydrogen Embrittlement Relief'), ('Masking', 'Masking'), ('Nickel Strip', 'Nickel Strip'), ('Oven Dry', 'Oven Dry'), ('Painting/Dry Film Coating', 'Painting/Dry Film Coating'), ('Passivation', 'Passivation'), ('Pre-Cleaning', 'Pre-Cleaning'), ('Pre-Pen Etching', 'Pre-Pen Etching'), ('Racking', 'Racking'), ('Rinsing', 'Rinsing'), ('Scrub Surface', 'Scrub Surface'), ('Sealing', 'Sealing'), ('Solvent Clean', 'Solvent Clean'), ('Spraying Rinse', 'Spray Rinse'), ('Stress Relief', 'Stress Relief'), ('Strip', 'Strip'), ('Thermal Treatment', 'Thermal Treatment'), ('Unmasking', 'Unmasking'), ('Unracking', 'Unracking'), ('Vacuum Cadmium & Aluminum IVD', 'Vacuum Cadmium & Aluminum IVD'), ('Water-Break Test', 'Water-Break Test')], max_length=255),
        ),
    ]
