# Generated by Django 5.1.3 on 2025-05-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0016_alter_parametertoberecorded_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='method',
            name='rectifier_notes',
            field=models.TextField(blank=True, help_text='Notes about ramp rate, strike procedure, amperage control, etc. for rectified processing.', null=True),
        ),
    ]
