# Generated by Django 5.1.3 on 2025-09-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0017_method_rectifier_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='method',
            name='is_strike_etch',
            field=models.BooleanField(default=False),
        ),
    ]
