# Generated by Django 5.2 on 2025-10-28 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0018_method_is_strike_etch'),
    ]

    operations = [
        migrations.AddField(
            model_name='method',
            name='is_bake_operation',
            field=models.BooleanField(default=False, help_text='True if this step is a bake/oven/thermal soak (like stress relief or post-plate bake).'),
        ),
        migrations.AddField(
            model_name='method',
            name='is_hydrogen_relief_operation',
            field=models.BooleanField(default=False, help_text='True if this bake is specifically a hydrogen embrittlement relief bake.'),
        ),
        migrations.AddField(
            model_name='method',
            name='is_masking_operation',
            field=models.BooleanField(default=False, help_text='True if this is a masking / demasking / tape / stop-off operation.'),
        ),
        migrations.AlterField(
            model_name='method',
            name='chemical',
            field=models.CharField(blank=True, help_text='Bath / chemical name or chemistry callout.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='method',
            name='description',
            field=models.TextField(blank=True, help_text='Operator-facing instruction / narrative work instruction.'),
        ),
        migrations.AlterField(
            model_name='method',
            name='immersion_time_max',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum immersion time.', null=True),
        ),
        migrations.AlterField(
            model_name='method',
            name='immersion_time_min',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum immersion time (seconds or minutes, define in SOP).', null=True),
        ),
        migrations.AlterField(
            model_name='method',
            name='is_rectified',
            field=models.BooleanField(default=False, help_text='Check if this step uses rectifier current (electroclean, plate, strike, etc.).'),
        ),
        migrations.AlterField(
            model_name='method',
            name='is_strike_etch',
            field=models.BooleanField(default=False, help_text='Check if this step is a strike or activation / etch prior to plate.'),
        ),
        migrations.AlterField(
            model_name='method',
            name='method_type',
            field=models.CharField(blank=True, choices=[('processing_tank', 'Processing Tank'), ('manual_method', 'Manual Method')], help_text='How this step is executed (tank vs manual, etc.).', max_length=50),
        ),
        migrations.AlterField(
            model_name='method',
            name='rectifier_notes',
            field=models.TextField(blank=True, help_text='Ramp, ASF, volts, polarity, anode/cathode setup, etc.', null=True),
        ),
        migrations.AlterField(
            model_name='method',
            name='temp_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum bath temp.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='method',
            name='temp_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum bath temp (°F or °C per your convention).', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='parametertoberecorded',
            name='description',
            field=models.TextField(blank=True, help_text='Details about what to record and how (units, gauge, limit).'),
        ),
        migrations.AlterField(
            model_name='parametertoberecorded',
            name='method',
            field=models.ForeignKey(blank=True, help_text='Which method/step this applies to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_parameters', to='methods.method'),
        ),
        migrations.AlterField(
            model_name='parametertoberecorded',
            name='title',
            field=models.CharField(choices=[('Abrasive Blasting', 'Abrasive Blasting'), ('Acid Desmut', 'Acid Desmut'), ('Air Dry', 'Air Dry'), ('Alkaline Clean', 'Alkaline Clean'), ('Anodize', 'Anodize'), ('Barrel Plating', 'Barrel Plating'), ('Brush Plating', 'Brush Plating'), ('Cad Strip', 'Cad Strip'), ('Chemical Milling', 'Chemical Milling'), ('Cleaning', 'Cleaning'), ('Chrome Strip', 'Chrome Strip'), ('Conversion Coating', 'Conversion Coating'), ('De-Oxidize/Pickle', 'De-Oxidize/Pickle'), ('Demasking', 'Demasking'), ('Electroless Plating', 'Electroless Plating'), ('Electrolytic Clean', 'Electrolytic Clean'), ('Electroplating', 'Electroplating'), ('Etching', 'Etching'), ('FOD Inspection', 'FOD Inspection'), ('Hydrogen Embrittlement Relief', 'Hydrogen Embrittlement Relief'), ('Masking', 'Masking'), ('Nickel Strip', 'Nickel Strip'), ('Oven Dry', 'Oven Dry'), ('Painting/Dry Film Coating', 'Painting/Dry Film Coating'), ('Passivation', 'Passivation'), ('Pre-Cleaning', 'Pre-Cleaning'), ('Pre-Pen Etching', 'Pre-Pen Etching'), ('Racking', 'Racking'), ('Rinsing', 'Rinsing'), ('Scrub Surface', 'Scrub Surface'), ('Sealing', 'Sealing'), ('Solvent Clean', 'Solvent Clean'), ('Spray Rinse', 'Spray Rinse'), ('Stress Relief', 'Stress Relief'), ('Strip', 'Strip'), ('Thermal Treatment', 'Thermal Treatment'), ('Unmasking', 'Unmasking'), ('Unracking', 'Unracking'), ('Vacuum Cadmium & Aluminum IVD', 'Vacuum Cadmium & Aluminum IVD'), ('Water-Break Test', 'Water-Break Test')], help_text='Short label for the parameter being recorded.', max_length=255),
        ),
    ]
