# Generated by Django 5.2 on 2025-10-28 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0019_method_is_bake_operation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametertoberecorded',
            name='is_nadcap_required',
            field=models.BooleanField(default=False, help_text='Required by Nadcap / customer audit? If yes, traveler can highlight it.'),
        ),
        migrations.AddField(
            model_name='parametertoberecorded',
            name='unit',
            field=models.CharField(blank=True, help_text='Optional unit text to print next to the blank (°F, amps, min, etc.).', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='method',
            name='chemical',
            field=models.CharField(blank=True, help_text='Bath chemistry / product / material callout (optional).', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='method',
            name='description',
            field=models.TextField(blank=True, help_text='Operator-facing work instruction / narrative for how to do this step.'),
        ),
        migrations.AlterField(
            model_name='method',
            name='immersion_time_max',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum contact/immersion time.', null=True),
        ),
        migrations.AlterField(
            model_name='method',
            name='immersion_time_min',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum contact/immersion time. Units defined by your SOP.', null=True),
        ),
        migrations.AlterField(
            model_name='method',
            name='is_bake_operation',
            field=models.BooleanField(default=False, help_text='True if this step is an oven/bake/stress-relief/thermal soak.'),
        ),
        migrations.AlterField(
            model_name='method',
            name='is_hydrogen_relief_operation',
            field=models.BooleanField(default=False, help_text='True if this bake is specifically Hydrogen Embrittlement Relief after plating.'),
        ),
        migrations.AlterField(
            model_name='method',
            name='is_masking_operation',
            field=models.BooleanField(default=False, help_text='True if this is masking, demasking, tape, or stop-off application/removal.'),
        ),
        migrations.AlterField(
            model_name='method',
            name='is_rectified',
            field=models.BooleanField(default=False, help_text='Check if this step uses a rectifier (current-controlled step like electroclean or plate).'),
        ),
        migrations.AlterField(
            model_name='method',
            name='is_strike_etch',
            field=models.BooleanField(default=False, help_text='Check if this is a strike / activation / etch prior to plating.'),
        ),
        migrations.AlterField(
            model_name='method',
            name='method_type',
            field=models.CharField(blank=True, choices=[('processing_tank', 'Processing Tank'), ('manual_method', 'Manual Method')], help_text='How this step is executed (tank vs. manual, etc.).', max_length=50),
        ),
        migrations.AlterField(
            model_name='method',
            name='rectifier_notes',
            field=models.TextField(blank=True, help_text='Ramp rate, ASF, volts, anode/cathode setup, polarity, etc.', null=True),
        ),
        migrations.AlterField(
            model_name='method',
            name='tank_name',
            field=models.CharField(blank=True, help_text='Tank name / line position / station ID if applicable.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='method',
            name='temp_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum bath or oven temperature.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='method',
            name='temp_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum bath or oven temperature (°F or °C per your standard).', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='method',
            name='title',
            field=models.CharField(blank=True, help_text='Operation title. You can match one of the predefined titles or write your own.', max_length=255),
        ),
        migrations.AlterField(
            model_name='parametertoberecorded',
            name='description',
            field=models.TextField(blank=True, help_text="Instruction for the blank line, e.g. 'Record plating current (amps)'."),
        ),
        migrations.AlterField(
            model_name='parametertoberecorded',
            name='method',
            field=models.ForeignKey(blank=True, help_text='Which Method step this applies to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_parameters', to='methods.method'),
        ),
        migrations.AlterField(
            model_name='parametertoberecorded',
            name='title',
            field=models.CharField(choices=[('Abrasive Blasting', 'Abrasive Blasting'), ('Acid Desmut', 'Acid Desmut'), ('Air Dry', 'Air Dry'), ('Alkaline Clean', 'Alkaline Clean'), ('Anodize', 'Anodize'), ('Barrel Plating', 'Barrel Plating'), ('Brush Plating', 'Brush Plating'), ('Cad Strip', 'Cad Strip'), ('Chemical Milling', 'Chemical Milling'), ('Cleaning', 'Cleaning'), ('Chrome Strip', 'Chrome Strip'), ('Conversion Coating', 'Conversion Coating'), ('De-Oxidize/Pickle', 'De-Oxidize/Pickle'), ('Demasking', 'Demasking'), ('Electroless Plating', 'Electroless Plating'), ('Electrolytic Clean', 'Electrolytic Clean'), ('Electroplating', 'Electroplating'), ('Etching', 'Etching'), ('FOD Inspection', 'FOD Inspection'), ('Hydrogen Embrittlement Relief', 'Hydrogen Embrittlement Relief'), ('Masking', 'Masking'), ('Nickel Strip', 'Nickel Strip'), ('Oven Dry', 'Oven Dry'), ('Painting/Dry Film Coating', 'Painting/Dry Film Coating'), ('Passivation', 'Passivation'), ('Pre-Cleaning', 'Pre-Cleaning'), ('Pre-Pen Etching', 'Pre-Pen Etching'), ('Racking', 'Racking'), ('Rinsing', 'Rinsing'), ('Scrub Surface', 'Scrub Surface'), ('Sealing', 'Sealing'), ('Solvent Clean', 'Solvent Clean'), ('Spray Rinse', 'Spray Rinse'), ('Stress Relief', 'Stress Relief'), ('Strip', 'Strip'), ('Thermal Treatment', 'Thermal Treatment'), ('Unmasking', 'Unmasking'), ('Unracking', 'Unracking'), ('Vacuum Cadmium & Aluminum IVD', 'Vacuum Cadmium & Aluminum IVD'), ('Water-Break Test', 'Water-Break Test')], help_text='Which type of operation this recordable applies to.', max_length=255),
        ),
    ]
