# Generated by Django 5.2 on 2025-11-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0020_parametertoberecorded_is_nadcap_required_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Abrasive Blasting', 'Abrasive Blasting'), ('Acid Desmut', 'Acid Desmut'), ('Air Dry', 'Air Dry'), ('Alkaline Clean', 'Alkaline Clean'), ('Anodize', 'Anodize'), ('Barrel Plating', 'Barrel Plating'), ('Brush Plating', 'Brush Plating'), ('Cad Strip', 'Cad Strip'), ('Chemical Milling', 'Chemical Milling'), ('Cleaning', 'Cleaning'), ('Chrome Strip', 'Chrome Strip'), ('Conversion Coating', 'Conversion Coating'), ('De-Oxidize/Pickle', 'De-Oxidize/Pickle'), ('Demasking', 'Demasking'), ('Electroless Plating', 'Electroless Plating'), ('Electrolytic Clean', 'Electrolytic Clean'), ('Electroplating', 'Electroplating'), ('Etching', 'Etching'), ('FOD Inspection', 'FOD Inspection'), ('Hydrogen Embrittlement Relief', 'Hydrogen Embrittlement Relief'), ('Masking', 'Masking'), ('Nickel Strip', 'Nickel Strip'), ('Oven Dry', 'Oven Dry'), ('Painting/Dry Film Coating', 'Painting/Dry Film Coating'), ('Passivation', 'Passivation'), ('Pre-Cleaning', 'Pre-Cleaning'), ('Pre-Pen Etching', 'Pre-Pen Etching'), ('Racking', 'Racking'), ('Rinsing', 'Rinsing'), ('Scrub Surface', 'Scrub Surface'), ('Sealing', 'Sealing'), ('Solvent Clean', 'Solvent Clean'), ('Spray Rinse', 'Spray Rinse'), ('Stress Relief', 'Stress Relief'), ('Strip', 'Strip'), ('Thermal Treatment', 'Thermal Treatment'), ('Unmasking', 'Unmasking'), ('Unracking', 'Unracking'), ('Vacuum Cadmium & Aluminum IVD', 'Vacuum Cadmium & Aluminum IVD'), ('Water-Break Test', 'Water-Break Test')], help_text='Category this template applies to.', max_length=255)),
                ('description', models.TextField(blank=True, help_text="What must be written on the traveler (e.g. 'Record immersion time (sec)').")),
                ('unit', models.CharField(blank=True, help_text='Unit to show next to blank (°F, amps, min, sec, etc.).', max_length=50, null=True)),
                ('is_nadcap_required', models.BooleanField(default=False, help_text='Check if this is Nadcap / customer required.')),
            ],
            options={
                'verbose_name': 'Parameter Template',
                'verbose_name_plural': 'Parameter Templates',
                'ordering': ['category'],
            },
        ),
        migrations.AddField(
            model_name='method',
            name='category',
            field=models.CharField(blank=True, choices=[('Abrasive Blasting', 'Abrasive Blasting'), ('Acid Desmut', 'Acid Desmut'), ('Air Dry', 'Air Dry'), ('Alkaline Clean', 'Alkaline Clean'), ('Anodize', 'Anodize'), ('Barrel Plating', 'Barrel Plating'), ('Brush Plating', 'Brush Plating'), ('Cad Strip', 'Cad Strip'), ('Chemical Milling', 'Chemical Milling'), ('Cleaning', 'Cleaning'), ('Chrome Strip', 'Chrome Strip'), ('Conversion Coating', 'Conversion Coating'), ('De-Oxidize/Pickle', 'De-Oxidize/Pickle'), ('Demasking', 'Demasking'), ('Electroless Plating', 'Electroless Plating'), ('Electrolytic Clean', 'Electrolytic Clean'), ('Electroplating', 'Electroplating'), ('Etching', 'Etching'), ('FOD Inspection', 'FOD Inspection'), ('Hydrogen Embrittlement Relief', 'Hydrogen Embrittlement Relief'), ('Masking', 'Masking'), ('Nickel Strip', 'Nickel Strip'), ('Oven Dry', 'Oven Dry'), ('Painting/Dry Film Coating', 'Painting/Dry Film Coating'), ('Passivation', 'Passivation'), ('Pre-Cleaning', 'Pre-Cleaning'), ('Pre-Pen Etching', 'Pre-Pen Etching'), ('Racking', 'Racking'), ('Rinsing', 'Rinsing'), ('Scrub Surface', 'Scrub Surface'), ('Sealing', 'Sealing'), ('Solvent Clean', 'Solvent Clean'), ('Spray Rinse', 'Spray Rinse'), ('Stress Relief', 'Stress Relief'), ('Strip', 'Strip'), ('Thermal Treatment', 'Thermal Treatment'), ('Unmasking', 'Unmasking'), ('Unracking', 'Unracking'), ('Vacuum Cadmium & Aluminum IVD', 'Vacuum Cadmium & Aluminum IVD'), ('Water-Break Test', 'Water-Break Test')], help_text='Select the process category to auto-attach required recorded parameters.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='parametertoberecorded',
            name='title',
            field=models.CharField(choices=[('Abrasive Blasting', 'Abrasive Blasting'), ('Acid Desmut', 'Acid Desmut'), ('Air Dry', 'Air Dry'), ('Alkaline Clean', 'Alkaline Clean'), ('Anodize', 'Anodize'), ('Barrel Plating', 'Barrel Plating'), ('Brush Plating', 'Brush Plating'), ('Cad Strip', 'Cad Strip'), ('Chemical Milling', 'Chemical Milling'), ('Cleaning', 'Cleaning'), ('Chrome Strip', 'Chrome Strip'), ('Conversion Coating', 'Conversion Coating'), ('De-Oxidize/Pickle', 'De-Oxidize/Pickle'), ('Demasking', 'Demasking'), ('Electroless Plating', 'Electroless Plating'), ('Electrolytic Clean', 'Electrolytic Clean'), ('Electroplating', 'Electroplating'), ('Etching', 'Etching'), ('FOD Inspection', 'FOD Inspection'), ('Hydrogen Embrittlement Relief', 'Hydrogen Embrittlement Relief'), ('Masking', 'Masking'), ('Nickel Strip', 'Nickel Strip'), ('Oven Dry', 'Oven Dry'), ('Painting/Dry Film Coating', 'Painting/Dry Film Coating'), ('Passivation', 'Passivation'), ('Pre-Cleaning', 'Pre-Cleaning'), ('Pre-Pen Etching', 'Pre-Pen Etching'), ('Racking', 'Racking'), ('Rinsing', 'Rinsing'), ('Scrub Surface', 'Scrub Surface'), ('Sealing', 'Sealing'), ('Solvent Clean', 'Solvent Clean'), ('Spray Rinse', 'Spray Rinse'), ('Stress Relief', 'Stress Relief'), ('Strip', 'Strip'), ('Thermal Treatment', 'Thermal Treatment'), ('Unmasking', 'Unmasking'), ('Unracking', 'Unracking'), ('Vacuum Cadmium & Aluminum IVD', 'Vacuum Cadmium & Aluminum IVD'), ('Water-Break Test', 'Water-Break Test')], help_text='General operation this recordable is associated with.', max_length=255),
        ),
    ]
