# Generated by Django 5.2 on 2025-11-18 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0021_parametertemplate_method_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametertoberecorded',
            name='title',
        ),
    ]
