# Generated by Django 5.2 on 2025-11-18 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0022_remove_parametertoberecorded_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametertoberecorded',
            name='method',
            field=models.ForeignKey(blank=True, help_text='Which Method step this applies to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recorded_parameters', to='methods.method'),
        ),
        migrations.AddConstraint(
            model_name='parametertoberecorded',
            constraint=models.UniqueConstraint(fields=('method', 'description'), name='unique_param_per_method'),
        ),
    ]
