# Generated by Django 5.2 on 2025-11-19 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0023_alter_parametertoberecorded_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametertemplate',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='parametertoberecorded',
            name='unit',
        ),
    ]
