# Generated by Django 5.2 on 2025-11-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0024_remove_parametertemplate_unit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='method',
            old_name='is_bake_operation',
            new_name='is_stress_relief_operation',
        ),
        migrations.AlterField(
            model_name='method',
            name='category',
            field=models.CharField(blank=True, choices=[('Pre-Cleaning', 'Pre-Cleaning'), ('Masking', 'Masking'), ('Abrasive Blasting', 'Abrasive Blasting'), ('Cleaning', 'Cleaning'), ('Rinsing', 'Rinsing'), ('De-Oxidize/Pickle', 'De-Oxidize/Pickle'), ('Electrolytic Clean', 'Electrolytic Clean'), ('Acid Desmut', 'Acid Desmut'), ('Etching', 'Etching'), ('Chemical Milling', 'Chemical Milling'), ('Conversion Coating', 'Conversion Coating'), ('Anodize', 'Anodize'), ('Sealing/Dying', 'Sealing/Dying'), ('Barrel Plating', 'Barrel Plating'), ('Brush Plating', 'Brush Plating'), ('Electroplating', 'Electroplating'), ('Painting/Dry Film Coating', 'Painting/Dry Film Coating'), ('Thermal Treatment', 'Thermal Treatment'), ('Vacuum Cadmium/Aluminum IVD', 'Vacuum Cadmium/Aluminum IVD'), ('Stress Relieve', 'Stress Relieve'), ('Hydrogen Embrittlement Relief', 'Hydrogen Embrittlement Relief')], help_text='Select the process category to auto-attach required recorded parameters.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='method',
            name='chemical',
            field=models.CharField(blank=True, help_text='Bath chemistry / product / material callout.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='method',
            name='immersion_time_min',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum contact/immersion time.', null=True),
        ),
        migrations.AlterField(
            model_name='method',
            name='temp_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum bath °F.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='method',
            name='temp_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum bath °F.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='parametertemplate',
            name='category',
            field=models.CharField(choices=[('Pre-Cleaning', 'Pre-Cleaning'), ('Masking', 'Masking'), ('Abrasive Blasting', 'Abrasive Blasting'), ('Cleaning', 'Cleaning'), ('Rinsing', 'Rinsing'), ('De-Oxidize/Pickle', 'De-Oxidize/Pickle'), ('Electrolytic Clean', 'Electrolytic Clean'), ('Acid Desmut', 'Acid Desmut'), ('Etching', 'Etching'), ('Chemical Milling', 'Chemical Milling'), ('Conversion Coating', 'Conversion Coating'), ('Anodize', 'Anodize'), ('Sealing/Dying', 'Sealing/Dying'), ('Barrel Plating', 'Barrel Plating'), ('Brush Plating', 'Brush Plating'), ('Electroplating', 'Electroplating'), ('Painting/Dry Film Coating', 'Painting/Dry Film Coating'), ('Thermal Treatment', 'Thermal Treatment'), ('Vacuum Cadmium/Aluminum IVD', 'Vacuum Cadmium/Aluminum IVD'), ('Stress Relieve', 'Stress Relieve'), ('Hydrogen Embrittlement Relief', 'Hydrogen Embrittlement Relief')], help_text='Category this template applies to.', max_length=100),
        ),
        migrations.AlterField(
            model_name='parametertemplate',
            name='description',
            field=models.TextField(blank=True, help_text="What must be written on the tech sheet (e.g. 'Record immersion time (sec)')."),
        ),
    ]
