# Generated by Django 5.2 on 2025-11-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0025_rename_is_bake_operation_method_is_stress_relief_operation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method',
            name='immersion_time_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum contact/immersion time.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='method',
            name='immersion_time_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum contact/immersion time.', max_digits=5, null=True),
        ),
    ]
