# Generated by Django 5.2 on 2025-11-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0026_alter_method_immersion_time_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method',
            name='temp_max',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum bath °F.', null=True),
        ),
        migrations.AlterField(
            model_name='method',
            name='temp_min',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum bath °F.', null=True),
        ),
    ]
