# Generated by Django 5.2 on 2025-11-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0027_alter_method_temp_max_alter_method_temp_min'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='parametertemplate',
            constraint=models.UniqueConstraint(fields=('category',), name='unique_parameter_template_category'),
        ),
    ]
