# Generated by Django 5.2 on 2025-11-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0028_parametertemplate_unique_parameter_template_category'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='method',
            constraint=models.UniqueConstraint(fields=('title',), name='unique_method_title'),
        ),
    ]
