# Generated by Django 5.2 on 2025-11-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0029_method_unique_method_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method',
            name='immersion_time_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum contact/immersion time.', max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='method',
            name='immersion_time_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum contact/immersion time.', max_digits=7, null=True),
        ),
    ]
