# Generated by Django 5.2 on 2025-11-20 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0030_alter_method_immersion_time_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method',
            name='immersion_time_max',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum contact/immersion time.', null=True),
        ),
        migrations.AlterField(
            model_name='method',
            name='immersion_time_min',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum contact/immersion time.', null=True),
        ),
    ]
