# Generated by Django 5.2 on 2025-11-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0031_alter_method_immersion_time_max_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='parametertemplate',
            name='unique_parameter_template_category',
        ),
        migrations.AddConstraint(
            model_name='parametertemplate',
            constraint=models.UniqueConstraint(fields=('category', 'description'), name='unique_parameter_template_per_category'),
        ),
    ]
