# Generated by Django 5.2 on 2025-11-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0032_remove_parametertemplate_unique_parameter_template_category_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='parametertemplate',
            name='unique_parameter_template_per_category',
        ),
        migrations.AddConstraint(
            model_name='parametertemplate',
            constraint=models.UniqueConstraint(fields=('category',), name='unique_parameter_template_category'),
        ),
    ]
