# Generated by Django 5.2 on 2025-12-08 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0033_remove_parametertemplate_unique_parameter_template_per_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='method',
            name='run_time_max',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum unattended/run time for this step (minutes).', null=True),
        ),
        migrations.AddField(
            model_name='method',
            name='run_time_min',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum unattended/run time for this step (minutes).', null=True),
        ),
        migrations.AddField(
            model_name='method',
            name='touch_time_max',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum operator touch time for this step (minutes).', null=True),
        ),
        migrations.AddField(
            model_name='method',
            name='touch_time_min',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum operator touch time for this step (minutes).', null=True),
        ),
    ]
