# Generated by Django 5.1.3 on 2024-11-29 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard',
            name='upload_file',
            field=models.FileField(blank=True, upload_to='standards/'),
        ),
    ]
