# Generated by Django 5.1.3 on 2024-11-29 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0007_periodictest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(blank=True, help_text='Optional method classification', max_length=255, null=True)),
                ('method_description', models.TextField(blank=True, help_text='Description of the method classification', null=True)),
                ('class_name', models.CharField(blank=True, help_text='Optional class classification', max_length=255, null=True)),
                ('class_description', models.TextField(blank=True, help_text='Description of the class classification', null=True)),
                ('type', models.CharField(blank=True, help_text='Optional type classification', max_length=255, null=True)),
                ('type_description', models.TextField(blank=True, help_text='Description of the type classification', null=True)),
                ('standard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='standard.standard')),
            ],
        ),
    ]
