# Generated by Django 5.1.3 on 2025-03-05 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0009_alter_periodictest_specification'),
    ]

    operations = [
        migrations.AddField(
            model_name='standard',
            name='previous_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='standard.standard'),
        ),
        migrations.AddField(
            model_name='standard',
            name='requires_process_review',
            field=models.BooleanField(default=False, help_text='Flagged when a new revision is issued.'),
        ),
        migrations.AlterUniqueTogether(
            name='standard',
            unique_together={('name', 'revision')},
        ),
        migrations.CreateModel(
            name='StandardRevisionNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Details of the standard update.')),
                ('notified_at', models.DateTimeField(auto_now_add=True)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='standard.standard')),
            ],
        ),
    ]
