# Generated by Django 5.1.1 on 2024-10-01 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parts', '0001_initial'),
        ('quality', '0001_initial'),
        ('specifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions', models.TextField()),
                ('tools_required', models.CharField(max_length=200)),
                ('safety_precautions', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.part')),
                ('quality_controls', models.ManyToManyField(blank=True, related_name='technical_sheets', to='quality.qualitycontrol')),
                ('specifications', models.ManyToManyField(related_name='technical_sheets', to='specifications.step')),
            ],
        ),
    ]
