# Generated by Django 5.1.3 on 2025-08-18 12:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FailureLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_report_number', models.CharField(max_length=100)),
                ('test_date', models.DateField()),
                ('original_po', models.CharField(blank=True, max_length=50, null=True)),
                ('test_result', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail')], max_length=4)),
                ('failure_reason', models.TextField(verbose_name='Reason for Failure & Investigation')),
                ('investigated_by', models.CharField(max_length=100)),
                ('test_type', models.CharField(choices=[('Replacement', 'Replacement'), ('Retest', 'Retest')], max_length=20)),
                ('retest_report_number', models.CharField(blank=True, max_length=100, null=True)),
                ('retest_date', models.DateField(blank=True, null=True)),
                ('retest_po', models.CharField(blank=True, max_length=50, null=True)),
                ('retest_result', models.CharField(blank=True, choices=[('Pass', 'Pass'), ('Fail', 'Fail')], max_length=4, null=True)),
                ('evidence_of_trend', models.TextField(blank=True, null=True)),
                ('reviewed_by', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-test_date'],
            },
        ),
        migrations.CreateModel(
            name='DailyTaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_task_templates_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DailyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_for', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('completed', models.BooleanField(default=False)),
                ('result', models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=4, null=True)),
                ('note', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_tasks_signed', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='periodic_testing.dailytasktemplate')),
            ],
            options={
                'ordering': ['template__name'],
                'unique_together': {('template', 'scheduled_for')},
            },
        ),
    ]
