# Generated by Django 5.1.3 on 2025-08-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FailureLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_report_number', models.CharField(max_length=100)),
                ('test_date', models.DateField()),
                ('test_result', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail')], max_length=4)),
                ('failure_reason', models.TextField(verbose_name='Reason for Failure & Investigation')),
                ('investigated_by', models.CharField(max_length=100)),
                ('test_type', models.CharField(choices=[('Replacement', 'Replacement'), ('Retest', 'Retest')], max_length=20)),
                ('retest_report_number', models.CharField(blank=True, max_length=100, null=True)),
                ('retest_date', models.DateField(blank=True, null=True)),
                ('retest_result', models.CharField(blank=True, choices=[('Pass', 'Pass'), ('Fail', 'Fail')], max_length=4, null=True)),
                ('evidence_of_trend', models.TextField(blank=True, null=True)),
                ('reviewed_by', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-test_date'],
            },
        ),
    ]
