# Generated by Django 5.2 on 2026-02-23 20:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0034_method_run_time_max_method_run_time_min_and_more'),
        ('periodic_testing', '0001_initial'),
        ('standard', '0022_alter_standardprocess_process_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodicTestTank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('periodic_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tank_links', to='standard.periodictest')),
                ('tank_method', models.ForeignKey(help_text='Select the tank Method that this periodic test applies to.', on_delete=django.db.models.deletion.PROTECT, related_name='periodic_test_links', to='methods.method')),
            ],
            options={
                'ordering': ['periodic_test__standard__name', 'periodic_test__name', 'tank_method__title'],
            },
        ),
        migrations.CreateModel(
            name='TankPanelSerial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(db_index=True, max_length=255, verbose_name="Panels' S/N")),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('tank_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panel_serials', to='periodic_testing.periodictesttank')),
            ],
            options={
                'ordering': ['tank_link__id', 'serial_number'],
            },
        ),
        migrations.CreateModel(
            name='PeriodicTestTankResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_on', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('performed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('passed', models.BooleanField(default=True)),
                ('report_pdf', models.FileField(blank=True, null=True, upload_to='periodic_tests/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodic_tank_results_reviewed', to=settings.AUTH_USER_MODEL)),
                ('tank_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='periodic_testing.periodictesttank')),
                ('panels_used', models.ManyToManyField(blank=True, related_name='results_used_in', to='periodic_testing.tankpanelserial')),
            ],
            options={
                'ordering': ['-performed_on', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='periodictesttank',
            constraint=models.UniqueConstraint(fields=('periodic_test', 'tank_method'), name='uniq_periodic_test_per_tank_method'),
        ),
        migrations.AddConstraint(
            model_name='tankpanelserial',
            constraint=models.UniqueConstraint(fields=('tank_link', 'serial_number'), name='uniq_panel_serial_per_tank_link'),
        ),
    ]
