# Generated by Django 5.1.3 on 2025-08-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodic_testing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='failurelog',
            name='original_po',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='failurelog',
            name='retest_po',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
