# Generated by Django 5.1.3 on 2025-08-07 19:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodic_testing', '0002_failurelog_original_po_failurelog_retest_po'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Task Name')),
                ('description', models.TextField(blank=True, verbose_name='Task Description')),
                ('driven_by_spec', models.TextField(blank=True, verbose_name='Task driven by Specification')),
                ('scheduled_for', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_tasks_signed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_tasks_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_for', '-completed', '-completed_at'],
            },
        ),
    ]
