# Generated by Django 5.1.3 on 2025-08-08 13:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodic_testing', '0004_dailytask_task_result'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailytask',
            options={'ordering': ['template__name']},
        ),
        migrations.AddField(
            model_name='dailytask',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dailytask',
            name='result',
            field=models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=4, null=True),
        ),
        migrations.CreateModel(
            name='DailyTaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_task_templates_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='dailytask',
            name='template',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='periodic_testing.dailytasktemplate'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='dailytask',
            unique_together={('template', 'scheduled_for')},
        ),
        migrations.RemoveField(
            model_name='dailytask',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='dailytask',
            name='description',
        ),
        migrations.RemoveField(
            model_name='dailytask',
            name='driven_by_spec',
        ),
        migrations.RemoveField(
            model_name='dailytask',
            name='name',
        ),
        migrations.RemoveField(
            model_name='dailytask',
            name='task_result',
        ),
    ]
