# Generated by Django 5.1.3 on 2025-03-07 18:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0003_remove_tank_created_at_remove_tank_scrubber_system_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tank',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tank',
            name='height',
            field=models.FloatField(blank=True, help_text='Height of the tank (inches)', null=True),
        ),
        migrations.AlterField(
            model_name='tank',
            name='length',
            field=models.FloatField(blank=True, help_text='Length of the tank (inches)', null=True),
        ),
        migrations.AlterField(
            model_name='tank',
            name='liquid_level',
            field=models.FloatField(blank=True, help_text='Liquid level (inches from the top)', null=True),
        ),
        migrations.AlterField(
            model_name='tank',
            name='width',
            field=models.FloatField(blank=True, help_text='Width of the tank (inches)', null=True),
        ),
    ]
