# Generated by Django 5.1.3 on 2025-03-07 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Production Line Name', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter tank name or identifier', max_length=255, unique=True)),
                ('chemical_composition', models.TextField(help_text='Describe the chemicals held in the tank')),
                ('length', models.FloatField(help_text='Length of the tank (inches)')),
                ('width', models.FloatField(help_text='Width of the tank (inches)')),
                ('height', models.FloatField(help_text='Height of the tank (inches)')),
                ('liquid_level', models.FloatField(help_text='Liquid level from top (inches)')),
                ('is_vented', models.BooleanField(default=False, help_text='Is the tank vented?')),
                ('scrubber_system', models.CharField(blank=True, help_text='Scrubber system name (if vented)', max_length=255, null=True)),
                ('max_amps', models.FloatField(blank=True, help_text='Maximum amperage applied in the tank', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('production_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tanks', to='tanks.productionline')),
            ],
        ),
    ]
