# Generated by Django 5.1.3 on 2025-03-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0002_alter_productionline_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tank',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tank',
            name='scrubber_system',
        ),
        migrations.RemoveField(
            model_name='tank',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='tank',
            name='scrubber',
            field=models.CharField(blank=True, help_text='Scrubber system (if applicable)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productionline',
            name='name',
            field=models.CharField(choices=[('l1', 'Line 1'), ('l2', 'Line 2'), ('l3', 'Line 3'), ('l4', 'Line 4'), ('l5', 'Line 5'), ('l6', 'Line 6'), ('l7', 'Line 7'), ('kl', 'Kernersville')], help_text='Select the production line', max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='tank',
            name='chemical_composition',
            field=models.TextField(help_text='Describe the chemical composition'),
        ),
        migrations.AlterField(
            model_name='tank',
            name='liquid_level',
            field=models.FloatField(help_text='Liquid level (inches from the top)'),
        ),
        migrations.AlterField(
            model_name='tank',
            name='max_amps',
            field=models.PositiveIntegerField(blank=True, help_text='Max amps (if applicable)', null=True),
        ),
        migrations.AlterField(
            model_name='tank',
            name='name',
            field=models.CharField(help_text='Enter the tank name', max_length=255, unique=True),
        ),
    ]
