# Generated by Django 5.1.3 on 2025-04-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('link_type', models.CharField(choices=[('spec', 'Specification Lookup'), ('change', 'Engineering Change Request')], max_length=10)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
