# Generated by Django 5.1.3 on 2024-12-01 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('standard', '0008_classification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=255, unique=True)),
                ('part_description', models.CharField(max_length=255)),
                ('part_revision', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_identity', models.CharField(choices=[('chrome_plate', 'Chrome Plate'), ('cadmium_plate', 'Cadmium Plate'), ('etch', 'Etch'), ('anodize', 'Anodize'), ('paint', 'Paint'), ('passivation', 'Passivation')], max_length=50)),
                ('alloy_with_heat_treat_condition', models.CharField(blank=True, max_length=255, null=True)),
                ('rework', models.BooleanField(default=False)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='part.part')),
                ('processing_standard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part_details', to='standard.standard')),
            ],
            options={
                'unique_together': {('part', 'job_identity', 'processing_standard')},
            },
        ),
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_order_with_revision', models.CharField(blank=True, max_length=255, null=True)),
                ('part_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('serial_or_lot_numbers', models.TextField(blank=True, null=True)),
                ('job_number', models.CharField(max_length=255, unique=True)),
                ('surface_repaired', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('part_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='part.partdetails')),
            ],
        ),
    ]
