# Generated by Django 5.1.3 on 2024-11-29 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('standard', '0008_classification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=255, unique=True)),
                ('part_description', models.CharField(max_length=255)),
                ('part_revision', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PartDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_export_controlled', models.BooleanField(blank=True, default=False, null=True)),
                ('job_identity', models.CharField(blank=True, max_length=255, null=True)),
                ('customer', models.CharField(blank=True, max_length=255, null=True)),
                ('prime_contractor', models.CharField(blank=True, max_length=255, null=True)),
                ('purchase_order_with_revision', models.CharField(blank=True, max_length=255, null=True)),
                ('part_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('serial_or_lot_numbers', models.TextField(blank=True, null=True)),
                ('date_of_job', models.DateField(blank=True, null=True)),
                ('job_number', models.CharField(blank=True, max_length=255, null=True)),
                ('alloy_with_heat_treat_condition', models.CharField(blank=True, max_length=255, null=True)),
                ('is_frozen_process', models.BooleanField(blank=True, default=False, null=True)),
                ('part', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='part.part')),
                ('processing_standard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='standard.standard')),
            ],
        ),
    ]
