# Generated by Django 5.1.3 on 2024-11-29 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partdetails',
            name='date_of_job',
        ),
        migrations.RemoveField(
            model_name='partdetails',
            name='job_number',
        ),
        migrations.RemoveField(
            model_name='partdetails',
            name='part_quantity',
        ),
        migrations.RemoveField(
            model_name='partdetails',
            name='purchase_order_with_revision',
        ),
        migrations.RemoveField(
            model_name='partdetails',
            name='serial_or_lot_numbers',
        ),
        migrations.AlterField(
            model_name='part',
            name='part_revision',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_order_with_revision', models.CharField(blank=True, max_length=255, null=True)),
                ('part_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('serial_or_lot_numbers', models.TextField(blank=True, null=True)),
                ('job_number', models.CharField(blank=True, max_length=255, null=True)),
                ('part', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_details', to='part.part')),
            ],
        ),
    ]
