# Generated by Django 5.1.3 on 2024-11-29 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0003_jobdetails_date_jobdetails_surface_repaired_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_details', to='part.part'),
        ),
    ]
