# Generated by Django 5.1.3 on 2024-11-29 18:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0004_alter_jobdetails_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='job_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
