# Generated by Django 5.1.3 on 2024-12-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0008_part_unique_part_revision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='part_number',
            field=models.CharField(max_length=255),
        ),
    ]
