# Generated by Django 5.1.3 on 2025-04-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0024_pdfsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='rework',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='job_identity',
            field=models.CharField(choices=[('alkaline clean', 'Alkaline Clean'), ('anodize', 'Anodize'), ('cadmium_plate', 'Cadmium Plate'), ('chemical conversion', 'Chemical Conversion'), ('chrome_plate', 'Chrome Plate'), ('cleaning', 'Cleaning'), ('etch', 'Etch'), ('ni_plate', 'Nickel Plate'), ('paint', 'Paint'), ('passivation', 'Passivation'), ('solvent_clean', 'Solvent Clean'), ('Strip', 'Strip')], max_length=50),
        ),
    ]
