# Generated by Django 5.1.3 on 2025-04-07 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0025_workorder_rework_alter_workorder_job_identity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ['part_number'], 'verbose_name': 'Part', 'verbose_name_plural': 'Parts'},
        ),
        migrations.AlterModelOptions(
            name='partstandard',
            options={'ordering': ['part'], 'verbose_name': 'Part Standard', 'verbose_name_plural': 'Part Standards'},
        ),
        migrations.AlterModelOptions(
            name='workorder',
            options={'ordering': ['work_order_number', 'part'], 'verbose_name': 'Work Order', 'verbose_name_plural': 'Work Orders'},
        ),
    ]
