# Generated by Django 5.2 on 2025-10-24 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0026_alter_part_options_alter_partstandard_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='current_density',
        ),
    ]
