# Generated by Django 5.2 on 2025-10-28 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0027_remove_workorder_current_density'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='amps',
        ),
    ]
