# Generated by Django 5.2 on 2025-11-19 16:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0028_remove_workorder_amps'),
        ('standard', '0019_alter_classification_plating_time_minutes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdfsettings',
            options={'verbose_name_plural': 'PDF Settings'},
        ),
        migrations.RemoveConstraint(
            model_name='partstandard',
            name='unique_part_standard_classification',
        ),
        migrations.AlterField(
            model_name='pdfsettings',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='standard.classification'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='job_identity',
            field=models.CharField(choices=[('alkaline_clean', 'Alkaline Clean'), ('anodize', 'Anodize'), ('cadmium_plate', 'Cadmium Plate'), ('chemical_conversion', 'Chemical Conversion'), ('chrome_plate', 'Chrome Plate'), ('cleaning', 'Cleaning'), ('etch', 'Etch'), ('ni_plate', 'Nickel Plate'), ('paint', 'Paint'), ('passivation', 'Passivation'), ('solvent_clean', 'Solvent Clean'), ('strip', 'Strip')], max_length=50),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='standard.standard'),
        ),
        migrations.AddConstraint(
            model_name='partstandard',
            constraint=models.UniqueConstraint(condition=models.Q(('classification__isnull', True)), fields=('part', 'standard', 'classification'), name='unique_part_standard_with_classification'),
        ),
        migrations.AddConstraint(
            model_name='partstandard',
            constraint=models.UniqueConstraint(condition=models.Q(('classification__isnull', True)), fields=('part', 'standard'), name='unique_part_standard_unclassified'),
        ),
    ]
