# Generated by Django 5.2 on 2025-11-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0029_alter_pdfsettings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='requires_hydrogen_relief',
            field=models.BooleanField(default=True, verbose_name='Hydrogen Embrittlement Relief Required'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='requires_masking',
            field=models.BooleanField(default=True, verbose_name='Masking Required'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='requires_stress_relief',
            field=models.BooleanField(default=True, verbose_name='Stress Relief Required'),
        ),
    ]
