# Generated by Django 5.2 on 2026-03-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0030_workorder_requires_hydrogen_relief_and_more'),
        ('standard', '0022_alter_standardprocess_process_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='partstandard',
            name='unique_part_standard_with_classification',
        ),
        migrations.AddConstraint(
            model_name='partstandard',
            constraint=models.UniqueConstraint(condition=models.Q(('classification__isnull', False)), fields=('part', 'standard', 'classification'), name='unique_part_standard_with_classification'),
        ),
    ]
