from django.urls import path
from . import views


urlpatterns = [
    path(
        '',
        views.part_list_view,
        name='part_list'
    ),
    path(
        'parts/<int:part_id>/',
        views.part_detail_view,
        name='part_detail'
    ),
    path(
        'process/standard/<int:part_standard_id>/print/',
        views.part_process_print_view,
        name='part_process_print'
    ),
    path(
        'parts/add/',
        views.part_create_view,
        name='part_create'
    ),
    path('parts/<int:part_id>/assign-standard/',
         views.part_assign_standard_view,
         name='part_assign_standard'
         ),
    path('standards/<int:standard_id>/classifications/json/',
         views.standard_classifications_json,
         name='standard_classifications_json'
         ),
    path('work_orders/<int:work_order_id>/',
         views.work_order_detail_view,
         name='work_order_detail'
         ),
    path('parts/<int:part_id>/work_orders/add/',
         views.work_order_create_view,
         name='work_order_create'
         ),
    path('work_orders/<int:work_order_id>/pdf/',
         views.work_order_print_steps_view,
         name='work_order_pdf'
         ),
    path(
        'parts/<int:part_id>/templates/',
        views.part_template_selection_view,
        name='part_template_selection'
    ),
    path(
        'templates/', 
        views.global_template_list_view, 
        name='global_template_list'
    ),
    path(
        'templates/process/<int:process_id>/select/', 
        views.template_selection_view, 
        name='template_selection'
    ),
    path(
        'templates/process/<int:process_id>/print/', 
        views.template_process_print_view, 
        name='template_process_print'
    ),
]
