# Generated by Django 5.1.3 on 2025-03-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0011_alter_method_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='method',
            options={'verbose_name': 'Method', 'verbose_name_plural': 'Methods'},
        ),
        migrations.AlterModelOptions(
            name='parametertoberecorded',
            options={'verbose_name': 'Recorded Parameter', 'verbose_name_plural': 'Recorded Parameters'},
        ),
        migrations.AlterField(
            model_name='method',
            name='description',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='method',
            name='method_type',
            field=models.CharField(blank=True, choices=[('processing_tank', 'Processing Tank'), ('manual_method', 'Manual Method')], max_length=50),
        ),
        migrations.AlterField(
            model_name='method',
            name='title',
            field=models.CharField(blank=True, choices=[('Abrasive Blasting', 'Abrasive Blasting'), ('Acid Desmut', 'Acid Desmut'), ('Air Dry', 'Air Dry'), ('Alkaline Clean', 'Alkaline Clean'), ('Anodize', 'Anodize'), ('Barrel Plating', 'Barrel Plating'), ('Brush Plating', 'Brush Plating'), ('Chemical Milling', 'Chemical Milling'), ('Cleaning', 'Cleaning'), ('Conversion Coating', 'Conversion Coating'), ('De-Oxidize/Pickle', 'De-Oxidize/Pickle'), ('Demasking', 'Demasking'), ('Electroless Plating', 'Electroless Plating'), ('Electrolytic Clean', 'Electrolytic Clean'), ('Electroplating', 'Electroplating'), ('Etching', 'Etching'), ('FOD Inpsection', 'FOD Inspection'), ('Hydrogen Embrittlement Relief', 'Hydrogen Embrittlement Relief'), ('Masking', 'Masking'), ('Oven Dry', 'Oven Dry'), ('Painting/Dry Film Coating', 'Painting/Dry Film Coating'), ('Pre-Cleaning', 'Pre-Cleaning'), ('Pre-Pen Etching', 'Pre-Pen Etching'), ('Racking', 'Racking'), ('Rinsing', 'Rinsing'), ('Scrub Surface', 'Scrub Surface'), ('Sealing', 'Sealing'), ('Solvent Clean', 'Solvent Clean'), ('Stress Relief', 'Stress Relief'), ('Thermal Treatment', 'Thermal Treatment'), ('Unracking', 'Unracking'), ('Vacuum Cadmium & Aluminum IVD', 'Vacuum Cadmium & Aluminum IVD'), ('Water-Break Test', 'Water-Break Test')], max_length=255),
        ),
        migrations.AlterField(
            model_name='parametertoberecorded',
            name='description',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parametertoberecorded',
            name='title',
            field=models.CharField(choices=[('Abrasive Blasting', 'Abrasive Blasting'), ('Acid Desmut', 'Acid Desmut'), ('Air Dry', 'Air Dry'), ('Alkaline Clean', 'Alkaline Clean'), ('Anodize', 'Anodize'), ('Barrel Plating', 'Barrel Plating'), ('Brush Plating', 'Brush Plating'), ('Chemical Milling', 'Chemical Milling'), ('Cleaning', 'Cleaning'), ('Conversion Coating', 'Conversion Coating'), ('De-Oxidize/Pickle', 'De-Oxidize/Pickle'), ('Demasking', 'Demasking'), ('Electroless Plating', 'Electroless Plating'), ('Electrolytic Clean', 'Electrolytic Clean'), ('Electroplating', 'Electroplating'), ('Etching', 'Etching'), ('FOD Inpsection', 'FOD Inspection'), ('Hydrogen Embrittlement Relief', 'Hydrogen Embrittlement Relief'), ('Masking', 'Masking'), ('Oven Dry', 'Oven Dry'), ('Painting/Dry Film Coating', 'Painting/Dry Film Coating'), ('Pre-Cleaning', 'Pre-Cleaning'), ('Pre-Pen Etching', 'Pre-Pen Etching'), ('Racking', 'Racking'), ('Rinsing', 'Rinsing'), ('Scrub Surface', 'Scrub Surface'), ('Sealing', 'Sealing'), ('Solvent Clean', 'Solvent Clean'), ('Stress Relief', 'Stress Relief'), ('Thermal Treatment', 'Thermal Treatment'), ('Unracking', 'Unracking'), ('Vacuum Cadmium & Aluminum IVD', 'Vacuum Cadmium & Aluminum IVD'), ('Water-Break Test', 'Water-Break Test')], max_length=255),
        ),
    ]
