# Generated by Django 5.1.3 on 2025-02-28 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masking', '0002_process_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaskingProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=255, unique=True)),
                ('part_number_masking_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='step',
            name='process',
        ),
        migrations.CreateModel(
            name='MaskingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masking_step_number', models.PositiveIntegerField()),
                ('masking_repair_title', models.CharField(max_length=255)),
                ('masking_description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='step_images/')),
                ('masking_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='masking.maskingprocess')),
            ],
            options={
                'ordering': ['masking_step_number'],
            },
        ),
        migrations.DeleteModel(
            name='Process',
        ),
        migrations.DeleteModel(
            name='Step',
        ),
    ]
