# Generated by Django 5.1.3 on 2025-03-04 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masking', '0006_alter_maskingprocess_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maskingprocess',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='maskingprocess',
            name='previous_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='masking.maskingprocess'),
        ),
        migrations.AddField(
            model_name='maskingprocess',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='maskingprocess',
            name='part_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='maskingprocess',
            unique_together={('part_number', 'version')},
        ),
    ]
