# Generated by Django 5.1.3 on 2025-08-20 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControlSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('process', models.CharField(blank=True, max_length=120, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChemicalSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chemical_name', models.CharField(max_length=120)),
                ('units', models.CharField(default='g/L', max_length=40)),
                ('target', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('min_val', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('max_val', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi-annual', 'Semi-Annually'), ('annual', 'Annually'), ('35d', 'Every 35 Days')], default='daily', max_length=20)),
                ('method', models.CharField(blank=True, max_length=240, null=True)),
                ('control_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chemical_specs', to='tank_controls.controlset')),
            ],
        ),
        migrations.CreateModel(
            name='CheckSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('check_type', models.CharField(choices=[('visual', 'Visual'), ('instrument', 'Instrument'), ('documentation', 'Documentation'), ('other', 'Other')], default='other', max_length=20)),
                ('method', models.TextField(blank=True, null=True)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi-annual', 'Semi-Annually'), ('annual', 'Annually'), ('35d', 'Every 35 Days')], default='daily', max_length=20)),
                ('control_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_specs', to='tank_controls.controlset')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodicTestSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi-annual', 'Semi-Annually'), ('annual', 'Annually'), ('35d', 'Every 35 Days')], default='monthly', max_length=20)),
                ('specification', models.TextField()),
                ('number_of_specimens', models.PositiveIntegerField()),
                ('material', models.CharField(max_length=255)),
                ('dimensions', models.CharField(max_length=255)),
                ('control_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodic_tests', to='tank_controls.controlset')),
            ],
            options={
                'ordering': ['control_set__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='controlset',
            name='tank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_sets', to='tank_controls.tank'),
        ),
        migrations.CreateModel(
            name='TemperatureSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_c', models.DecimalField(decimal_places=2, max_digits=6)),
                ('max_c', models.DecimalField(decimal_places=2, max_digits=6)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi-annual', 'Semi-Annually'), ('annual', 'Annually'), ('35d', 'Every 35 Days')], default='daily', max_length=20)),
                ('control_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temperature_specs', to='tank_controls.controlset')),
            ],
        ),
    ]
