# Generated by Django 5.1.3 on 2025-08-22 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tank_controls', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkspec',
            options={'ordering': ['control_set__name', 'name']},
        ),
        migrations.AlterModelOptions(
            name='chemicalspec',
            options={'ordering': ['control_set__name', 'chemical_name']},
        ),
        migrations.AlterModelOptions(
            name='controlset',
            options={'ordering': ['tank__name', 'name']},
        ),
        migrations.AlterModelOptions(
            name='tank',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='temperaturespec',
            options={'ordering': ['control_set__name', 'min_c', 'max_c']},
        ),
        migrations.AlterField(
            model_name='chemicalspec',
            name='method',
            field=models.CharField(blank=True, help_text='How to test/titrate, notes, etc.', max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='tank',
            name='process',
            field=models.CharField(blank=True, help_text='e.g., Cadmium, Chrome, Anodize', max_length=120, null=True),
        ),
        migrations.CreateModel(
            name='PeriodicTestExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_on', models.DateField(auto_now_add=True)),
                ('passed', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodic_test_executions', to=settings.AUTH_USER_MODEL)),
                ('test_spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='tank_controls.periodictestspec')),
            ],
            options={
                'ordering': ['-performed_on'],
            },
        ),
    ]
