# Generated by Django 5.1.3 on 2025-03-03 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masking', '0003_maskingprocess_remove_step_process_maskingstep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maskingstep',
            name='masking_process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masking_steps', to='masking.maskingprocess'),
        ),
        migrations.DeleteModel(
            name='MaskingProfile',
        ),
    ]
