# Generated by Django 5.1.3 on 2025-03-28 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0008_rackpm_created_at_rackpm_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pmtask',
            options={'verbose_name': 'PM Task Template', 'verbose_name_plural': 'PM Task Templates'},
        ),
        migrations.AlterModelOptions(
            name='rack',
            options={'verbose_name': 'Rack Info', 'verbose_name_plural': 'Racks'},
        ),
        migrations.AlterModelOptions(
            name='rackphoto',
            options={'verbose_name': 'Rack Photo', 'verbose_name_plural': 'Rack Photos'},
        ),
        migrations.AlterModelOptions(
            name='rackpm',
            options={'verbose_name': 'Log PM Entry', 'verbose_name_plural': 'Log PM Entries'},
        ),
        migrations.AlterModelOptions(
            name='rackpmplan',
            options={'verbose_name': 'PM Schedule', 'verbose_name_plural': 'PM Schedules'},
        ),
    ]
