# Generated by Django 5.1.3 on 2024-12-02 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0001_initial'),
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_steps', to='methods.method')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='process.process')),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
    ]
