# Generated by Django 5.2 on 2025-11-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0005_alter_process_options_alter_processstep_options_and_more'),
        ('standard', '0019_alter_classification_plating_time_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='process',
            index=models.Index(fields=['standard', 'classification'], name='process_pro_standar_e71934_idx'),
        ),
        migrations.AddConstraint(
            model_name='process',
            constraint=models.UniqueConstraint(fields=('standard', 'classification'), name='uniq_process_per_standard_classification'),
        ),
    ]
