# Generated by Django 5.2 on 2025-11-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0021_parametertemplate_method_category_and_more'),
        ('process', '0006_alter_process_created_at_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='processstep',
            index=models.Index(fields=['process', 'step_number'], name='process_pro_process_d8eee3_idx'),
        ),
        migrations.AddConstraint(
            model_name='processstep',
            constraint=models.UniqueConstraint(fields=('process', 'step_number'), name='uniq_step_number_per_process'),
        ),
        migrations.AddConstraint(
            model_name='processstep',
            constraint=models.CheckConstraint(condition=models.Q(('step_number__gte', 1)), name='step_number_gte_1'),
        ),
    ]
