# Generated by Django 5.2 on 2025-11-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0007_processstep_process_pro_process_d8eee3_idx_and_more'),
        ('standard', '0019_alter_classification_plating_time_minutes_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='process',
            name='uniq_process_per_standard_classification',
        ),
        migrations.AddConstraint(
            model_name='process',
            constraint=models.UniqueConstraint(fields=('standard', 'classification'), name='uniq_process_with_classification'),
        ),
        migrations.AddConstraint(
            model_name='process',
            constraint=models.UniqueConstraint(condition=models.Q(('classification__isnull', True)), fields=('standard',), name='uniq_unclassified_process_per_standard'),
        ),
    ]
