# Generated by Django 5.2 on 2025-11-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0008_remove_process_uniq_process_per_standard_classification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='is_template',
            field=models.BooleanField(default=False, help_text='If checked, this Process can be printed as an untracked template (not a Work Order).'),
        ),
    ]
