# Generated by Django 5.2 on 2025-12-01 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0009_process_is_template'),
        ('standard', '0021_alter_classification_standard'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='standard_process',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='standard.standardprocess'),
            preserve_default=False,
        ),
    ]
