# Generated by Django 5.2 on 2026-03-10 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0010_process_standard_process'),
        ('standard', '0022_alter_standardprocess_process_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='standard_process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processes', to='standard.standardprocess'),
        ),
    ]
