# Generated by Django 5.1.3 on 2024-12-02 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('standard', '0008_classification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='standard.classification')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='standard.standard')),
            ],
            options={
                'unique_together': {('standard', 'classification')},
            },
        ),
    ]
