# Generated by Django 5.1.3 on 2025-02-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0003_alter_processstep_step_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processstep',
            name='step_number',
            field=models.PositiveIntegerField(),
        ),
    ]
