# Generated by Django 5.2 on 2025-12-30 13:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drawing_number', models.CharField(db_index=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('revision', models.CharField(db_index=True, max_length=50)),
                ('pdf_file', models.FileField(upload_to='drawings/')),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('superseded_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_drawings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['drawing_number', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DrawingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField(db_index=True, help_text='1-based page number in the PDF.', validators=[django.core.validators.MinValueValidator(1)])),
                ('label', models.CharField(max_length=120)),
                ('geom_type', models.CharField(choices=[('polygon', 'Polygon'), ('rect', 'Rectangle')], default='polygon', max_length=20)),
                ('geometry', models.JSONField(help_text='Normalized SVG geometry in 0..1 coordinates.')),
                ('area_value', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('area_unit', models.CharField(choices=[('in2', 'in²'), ('ft2', 'ft²')], default='in2', max_length=10)),
                ('is_exclusion_zone', models.BooleanField(default=False, help_text='If true, this zone subtracts from plating area when selected.')),
                ('default_selected', models.BooleanField(default=True, help_text='Default selection state for operators.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_drawing_zones', to=settings.AUTH_USER_MODEL)),
                ('drawing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='drawings.drawing')),
            ],
            options={
                'ordering': ['drawing', 'page_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PlatingAreaCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(blank=True, db_index=True, max_length=100)),
                ('process_name', models.CharField(blank=True, db_index=True, help_text='e.g., Cadmium Plate, Hard Chrome, Nickel, etc.', max_length=100)),
                ('gross_area_value', models.DecimalField(decimal_places=4, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('excluded_area_value', models.DecimalField(decimal_places=4, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('net_area_value', models.DecimalField(decimal_places=4, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('area_unit', models.CharField(choices=[('in2', 'in²'), ('ft2', 'ft²')], default='in2', max_length=10)),
                ('basis', models.CharField(blank=True, help_text="e.g., 'manual calc', 'drawing note', 'engineering estimate'.", max_length=50)),
                ('assumptions', models.TextField(blank=True, help_text='What is included/excluded, both sides, threads, holes, masking assumptions, etc.')),
                ('drawing_reference', models.CharField(blank=True, help_text="e.g., 'Rev C Note 12'", max_length=100)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_plating_cards', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_plating_cards', to=settings.AUTH_USER_MODEL)),
                ('drawing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plating_cards', to='drawings.drawing')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatingCardZoneSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected', models.BooleanField(default=True)),
                ('plating_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_selections', to='drawings.platingareacard')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plating_card_links', to='drawings.drawingzone')),
            ],
        ),
        migrations.AddConstraint(
            model_name='drawing',
            constraint=models.UniqueConstraint(fields=('drawing_number', 'revision'), name='uniq_drawing_number_revision'),
        ),
        migrations.AddIndex(
            model_name='drawingzone',
            index=models.Index(fields=['drawing', 'page_number'], name='drawings_dr_drawing_04912c_idx'),
        ),
        migrations.AddIndex(
            model_name='platingareacard',
            index=models.Index(fields=['part_number', 'process_name'], name='drawings_pl_part_nu_050be5_idx'),
        ),
        migrations.AddIndex(
            model_name='platingareacard',
            index=models.Index(fields=['drawing', 'process_name'], name='drawings_pl_drawing_e65706_idx'),
        ),
        migrations.AddConstraint(
            model_name='platingcardzoneselection',
            constraint=models.UniqueConstraint(fields=('plating_card', 'zone'), name='uniq_platingcard_zone'),
        ),
    ]
