# Generated by Django 5.2 on 2025-12-30 19:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drawingzone',
            options={'ordering': ['drawing', 'id']},
        ),
        migrations.RemoveIndex(
            model_name='drawingzone',
            name='drawings_dr_drawing_04912c_idx',
        ),
        migrations.RemoveIndex(
            model_name='platingareacard',
            name='drawings_pl_part_nu_050be5_idx',
        ),
        migrations.RemoveIndex(
            model_name='platingareacard',
            name='drawings_pl_drawing_e65706_idx',
        ),
        migrations.RemoveField(
            model_name='drawing',
            name='page_count',
        ),
        migrations.RemoveField(
            model_name='drawingzone',
            name='page_number',
        ),
        migrations.RemoveField(
            model_name='platingareacard',
            name='process_name',
        ),
        migrations.AddField(
            model_name='platingareacard',
            name='plating_type',
            field=models.CharField(choices=[('chrome', 'Chrome Plate'), ('nickel', 'Nickel Plate'), ('cadmium', 'Cadmium Plate')], db_index=True, default='chrome', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='platingareacard',
            name='variation',
            field=models.CharField(db_index=True, default='DEFAULT', help_text='Distinguishes different area presets for the same drawing and plating type.', max_length=60),
        ),
        migrations.AlterField(
            model_name='drawingzone',
            name='default_selected',
            field=models.BooleanField(default=True, help_text='Default selection state for operators (used as baseline).'),
        ),
        migrations.AlterField(
            model_name='platingareacard',
            name='basis',
            field=models.CharField(blank=True, help_text='e.g., manual calc, drawing note, engineering estimate.', max_length=50),
        ),
        migrations.AlterField(
            model_name='platingareacard',
            name='drawing_reference',
            field=models.CharField(blank=True, help_text='e.g., Rev C Note 12', max_length=100),
        ),
        migrations.AlterField(
            model_name='platingareacard',
            name='part_number',
            field=models.CharField(blank=True, db_index=True, help_text='Optional. Use if you want to filter by part number separately from drawing number.', max_length=100),
        ),
        migrations.AddIndex(
            model_name='drawingzone',
            index=models.Index(fields=['drawing'], name='drawings_dr_drawing_2902ab_idx'),
        ),
        migrations.AddIndex(
            model_name='platingareacard',
            index=models.Index(fields=['drawing', 'plating_type', 'variation'], name='drawings_pl_drawing_c3f61e_idx'),
        ),
        migrations.AddIndex(
            model_name='platingareacard',
            index=models.Index(fields=['part_number', 'plating_type', 'variation'], name='drawings_pl_part_nu_05044b_idx'),
        ),
        migrations.AddIndex(
            model_name='platingcardzoneselection',
            index=models.Index(fields=['plating_card'], name='drawings_pl_plating_bfa905_idx'),
        ),
        migrations.AddIndex(
            model_name='platingcardzoneselection',
            index=models.Index(fields=['zone'], name='drawings_pl_zone_id_7627fe_idx'),
        ),
        migrations.AddConstraint(
            model_name='platingareacard',
            constraint=models.UniqueConstraint(fields=('drawing', 'plating_type', 'variation'), name='uniq_card_drawing_plating_variation'),
        ),
    ]
