# Generated by Django 5.2 on 2025-12-30 20:44

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0002_alter_drawingzone_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drawingzone',
            options={'ordering': ['drawing', 'plating_type', 'page_number', 'id']},
        ),
        migrations.AlterModelOptions(
            name='platingareacard',
            options={'ordering': ['drawing', 'plating_type']},
        ),
        migrations.RemoveConstraint(
            model_name='platingareacard',
            name='uniq_card_drawing_plating_variation',
        ),
        migrations.RemoveIndex(
            model_name='drawingzone',
            name='drawings_dr_drawing_2902ab_idx',
        ),
        migrations.RemoveIndex(
            model_name='platingareacard',
            name='drawings_pl_drawing_c3f61e_idx',
        ),
        migrations.RemoveIndex(
            model_name='platingareacard',
            name='drawings_pl_part_nu_05044b_idx',
        ),
        migrations.RemoveIndex(
            model_name='platingcardzoneselection',
            name='drawings_pl_plating_bfa905_idx',
        ),
        migrations.RemoveIndex(
            model_name='platingcardzoneselection',
            name='drawings_pl_zone_id_7627fe_idx',
        ),
        migrations.RemoveField(
            model_name='platingareacard',
            name='variation',
        ),
        migrations.AddField(
            model_name='drawingzone',
            name='page_number',
            field=models.PositiveIntegerField(db_index=True, default=1, help_text='1-based page number in the PDF (defaults to 1).', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='drawingzone',
            name='plating_type',
            field=models.CharField(choices=[('chrome', 'Chrome Plate'), ('nickel', 'Nickel Plate'), ('cadmium', 'Cadmium Plate')], db_index=True, default='chrome', help_text='Plating type for this zone (set by annotation session).', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='drawingzone',
            name='default_selected',
            field=models.BooleanField(default=True, help_text='Default selection state for operators.'),
        ),
        migrations.AlterField(
            model_name='drawingzone',
            name='is_exclusion_zone',
            field=models.BooleanField(default=False, help_text='If true, subtracts from plating area when selected.'),
        ),
        migrations.AlterField(
            model_name='platingareacard',
            name='assumptions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='platingareacard',
            name='basis',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='platingareacard',
            name='drawing_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='platingareacard',
            name='part_number',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='drawingzone',
            index=models.Index(fields=['drawing', 'plating_type'], name='drawings_dr_drawing_ac0b41_idx'),
        ),
        migrations.AddIndex(
            model_name='drawingzone',
            index=models.Index(fields=['drawing', 'plating_type', 'page_number'], name='drawings_dr_drawing_80611b_idx'),
        ),
        migrations.AddIndex(
            model_name='platingareacard',
            index=models.Index(fields=['drawing', 'plating_type'], name='drawings_pl_drawing_4f96f7_idx'),
        ),
        migrations.AddConstraint(
            model_name='platingareacard',
            constraint=models.UniqueConstraint(fields=('drawing', 'plating_type'), name='uniq_card_drawing_platingtype'),
        ),
    ]
