# Generated by Django 5.1.3 on 2024-12-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='method',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='method',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='method',
            name='chemical',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='method',
            name='immersion_time_max',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='method',
            name='immersion_time_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='method',
            name='is_rectified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='method',
            name='tank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='method',
            name='temp_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='method',
            name='temp_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='method',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
