# Generated by Django 5.1.3 on 2024-12-19 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0002_remove_method_created_at_remove_method_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PARAMETER_TO_BE_RECORDED',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('title_parameter', models.CharField(max_length=255)),
                ('method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='methods.method')),
            ],
        ),
    ]
