# Generated by Django 5.1.3 on 2024-12-19 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0003_parameter_to_be_recorded'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterToBeRecorded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short name or label for the parameter.', max_length=100)),
                ('description', models.CharField(help_text='Detailed description of the parameter being recorded.', max_length=255)),
                ('method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='methods.method')),
            ],
        ),
        migrations.DeleteModel(
            name='PARAMETER_TO_BE_RECORDED',
        ),
    ]
