# Generated by Django 5.2 on 2025-11-07 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('part', '0028_remove_workorder_amps'),
        ('standard', '0019_alter_classification_plating_time_minutes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number_text', models.CharField(blank=True, help_text='Part number as written on paperwork or template.', max_length=255)),
                ('spec_or_template_name', models.CharField(blank=True, help_text='Template/spec name when no part record exists (e.g. strip chrome template).', max_length=255)),
                ('standard_text', models.CharField(blank=True, help_text='Snapshot of standard description/name.', max_length=255)),
                ('classification_text', models.CharField(blank=True, help_text='Snapshot of classification used (method/class/type).', max_length=255)),
                ('spec_revision', models.CharField(blank=True, help_text='Spec revision used on the day of processing.', max_length=50)),
                ('work_order_number', models.CharField(blank=True, help_text='WO/job/traveler number as written by operator.', max_length=100)),
                ('process_name', models.CharField(help_text='Name of the operation performed (e.g. Cad plate, Strip chrome, Pre-pen etch).', max_length=150)),
                ('repaired_surface', models.CharField(blank=True, help_text='Section/surface of the part that was processed/repaired.', max_length=150)),
                ('date_of_plating', models.DateField(help_text='Processing date used for logbook, plots, and KPIs.')),
                ('plating_end_time', models.DateTimeField(help_text='Actual removal from bath / end of process. Operator-editable.')),
                ('quantity_processed', models.PositiveIntegerField(default=1, help_text='Usually 1, but kept numeric for completeness.')),
                ('lot_number', models.CharField(blank=True, help_text='Lot/batch identifier from paperwork.', max_length=100)),
                ('is_rework', models.BooleanField(default=False)),
                ('rework_source', models.CharField(blank=True, choices=[('TRAVELER', 'Traveler labeled rework'), ('OPERATOR', 'Operator identified rework'), ('SUPERVISOR', 'Supervisor tagged as rework'), ('UNKNOWN', 'Unknown source')], max_length=20)),
                ('rework_reason', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='standard.classification')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_runs_created', to=settings.AUTH_USER_MODEL)),
                ('part', models.ForeignKey(blank=True, help_text='Link to part when it exists in the system.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='part.part')),
                ('standard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='standard.standard')),
                ('technician', models.ForeignKey(blank=True, help_text='Operator who performed/logged the run.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_runs', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_runs_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Process Run',
                'verbose_name_plural': 'Process Runs',
                'ordering': ['-date_of_plating', '-plating_end_time'],
            },
        ),
        migrations.CreateModel(
            name='EmbrittlementRelief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('furnace_number', models.CharField(blank=True, max_length=100)),
                ('linked_operation', models.CharField(blank=True, choices=[('MACHINING', 'Machining operation'), ('PLATING', 'Plating operation'), ('INSPECTION', 'Inspection operation')], max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('process_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embrittlement_relief', to='logbook.processrun')),
            ],
        ),
        migrations.CreateModel(
            name='ControlInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_name', models.CharField(help_text="Name of the inspection/test (e.g. 'Thickness', 'Visual', 'Adhesion').", max_length=150)),
                ('inspection_spec', models.CharField(blank=True, help_text='Specification + paragraph as performed (spec is revision-controlled).', max_length=255)),
                ('sample_size', models.PositiveIntegerField(default=1, help_text='Number of parts tested for this inspection.')),
                ('inspection_result', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'Not OK')], max_length=10)),
                ('inspected_at', models.DateTimeField(blank=True, help_text='When the inspection was actually done (operator may enter later).', null=True)),
                ('comments', models.TextField(blank=True)),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_inspections_performed', to=settings.AUTH_USER_MODEL)),
                ('process_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_inspections', to='logbook.processrun')),
            ],
            options={
                'verbose_name': 'Control Inspection',
                'verbose_name_plural': 'Control Inspections',
            },
        ),
    ]
