# Generated by Django 5.2 on 2025-11-07 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0001_initial'),
        ('part', '0028_remove_workorder_amps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processrun',
            name='spec_or_template_name',
        ),
        migrations.AlterField(
            model_name='processrun',
            name='classification_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='processrun',
            name='date_of_plating',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='processrun',
            name='lot_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='processrun',
            name='part',
            field=models.ForeignKey(blank=True, help_text='Select if the part exists in the system.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='part.part'),
        ),
        migrations.AlterField(
            model_name='processrun',
            name='part_number_text',
            field=models.CharField(blank=True, help_text='Enter part number / template name when part is not in the system.', max_length=255),
        ),
        migrations.AlterField(
            model_name='processrun',
            name='process_name',
            field=models.CharField(help_text='Operation performed (Cad plate, Strip chrome, Pre-pen etch, etc.)', max_length=150),
        ),
        migrations.AlterField(
            model_name='processrun',
            name='quantity_processed',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='processrun',
            name='spec_revision',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='processrun',
            name='standard_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='processrun',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='processrun',
            name='work_order_number',
            field=models.CharField(blank=True, help_text='WO / traveler number as written.', max_length=100),
        ),
    ]
