# Generated by Django 5.2 on 2025-11-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0002_remove_processrun_spec_or_template_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processrun',
            name='part',
        ),
        migrations.AlterField(
            model_name='processrun',
            name='part_number_text',
            field=models.CharField(help_text='Part number / template / specification identifier exactly as on the traveler.', max_length=255),
        ),
        migrations.AlterField(
            model_name='processrun',
            name='process_name',
            field=models.CharField(help_text='Operation performed (e.g. Cad plate, Strip chrome, Pre-pen etch).', max_length=150),
        ),
        migrations.AlterField(
            model_name='processrun',
            name='spec_revision',
            field=models.CharField(blank=True, help_text='Revision of the spec used for this run.', max_length=50),
        ),
    ]
