# Generated by Django 5.2 on 2025-11-07 20:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0003_remove_processrun_part_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processrun',
            options={'ordering': ['-date_of_process', '-plating_end_time'], 'verbose_name': 'Process Run', 'verbose_name_plural': 'Process Runs'},
        ),
        migrations.RemoveField(
            model_name='processrun',
            name='date_of_plating',
        ),
        migrations.AddField(
            model_name='processrun',
            name='date_of_process',
            field=models.DateField(default=django.utils.timezone.now, help_text='Calendar date when the processing was performed/logged.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='processrun',
            name='plating_end_time',
            field=models.DateTimeField(blank=True, help_text='Actual end time / removal from bath when applicable', null=True),
        ),
    ]
