# Generated by Django 5.2 on 2025-11-07 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0004_alter_processrun_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processrun',
            name='classification',
        ),
        migrations.RemoveField(
            model_name='processrun',
            name='standard',
        ),
        migrations.AlterField(
            model_name='processrun',
            name='classification_text',
            field=models.CharField(blank=True, help_text='Classification, method, or type description per standard.', max_length=255),
        ),
        migrations.AlterField(
            model_name='processrun',
            name='part_number_text',
            field=models.CharField(help_text='Part number', max_length=255),
        ),
        migrations.AlterField(
            model_name='processrun',
            name='standard_text',
            field=models.CharField(blank=True, help_text='Standard or specification name. (e.g. AMS 2400, MIL-A-8625, etc...)', max_length=255),
        ),
    ]
