# Generated by Django 5.2 on 2025-11-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0005_remove_processrun_classification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_process', models.DateField()),
                ('part_number', models.CharField(max_length=255)),
                ('process_name', models.CharField(max_length=150)),
                ('work_order_number', models.CharField(blank=True, max_length=100)),
                ('repaired_surface', models.CharField(blank=True, max_length=150)),
                ('standard_text', models.CharField(blank=True, max_length=255)),
                ('classification_text', models.CharField(blank=True, max_length=255)),
                ('spec_revision', models.CharField(blank=True, max_length=50)),
                ('quantity_processed', models.PositiveIntegerField(default=1)),
                ('lot_number', models.CharField(blank=True, max_length=100)),
                ('process_end_time', models.DateTimeField(blank=True, null=True)),
                ('is_rework', models.BooleanField(default=False)),
                ('rework_reason', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_of_process', '-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='embrittlementrelief',
            name='process_run',
        ),
        migrations.RemoveField(
            model_name='processrun',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='processrun',
            name='technician',
        ),
        migrations.RemoveField(
            model_name='processrun',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='ControlInspection',
        ),
        migrations.DeleteModel(
            name='EmbrittlementRelief',
        ),
        migrations.DeleteModel(
            name='ProcessRun',
        ),
    ]
