# Generated by Django 5.2 on 2025-11-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0006_logentry_remove_embrittlementrelief_process_run_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='failure_mode',
            field=models.CharField(choices=[('NONE', 'None'), ('MASKING_ERROR', 'Masking error / leak'), ('WRONG_SECTION', 'Wrong section / wrong area processed'), ('LOW_THICKNESS', 'Low thickness'), ('HIGH_THICKNESS', 'High thickness'), ('NON_UNIFORM', 'Non-uniform coverage'), ('ADHESION_FAIL', 'Adhesion failure / peel'), ('CONTAMINATION', 'Contamination / roughness / pitting'), ('BURNED_AREA', 'Burned area / overheating'), ('ETCH_DAMAGE', 'Etch or strip damage'), ('POST_TREAT_ERROR', 'Post-treatment / bake / rinse error')], default='NONE', help_text="Observed failure mode or 'None' if acceptable.", max_length=30),
        ),
        migrations.AddField(
            model_name='logentry',
            name='is_accept',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='process_name',
            field=models.CharField(blank=True, choices=[('alkaline_clean', 'Alkaline Clean'), ('anodize', 'Anodize'), ('cadmium_plate', 'Cadmium Plate'), ('chemical_conversion', 'Chemical Conversion'), ('chrome_plate', 'Chrome Plate'), ('cleaning', 'Cleaning'), ('etch', 'Etch'), ('ni_plate', 'Nickel Plate'), ('paint', 'Paint'), ('passivation', 'Passivation'), ('solvent_clean', 'Solvent Clean'), ('strip', 'Strip')], max_length=50),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='rework_reason',
            field=models.CharField(blank=True, choices=[('TRAVELER', 'Traveler labeled rework'), ('OPERATOR', 'Operator identified rework'), ('SUPERVISOR', 'Supervisor tagged as rework'), ('UNKNOWN', 'Unknown source')], max_length=20),
        ),
    ]
