# Generated by Django 5.2 on 2025-11-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0007_logentry_failure_mode_logentry_is_accept_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='failure_mode',
            field=models.CharField(choices=[('NONE', 'None'), ('MASKING_ERROR', 'Masking error / leak'), ('WRONG_SECTION', 'Wrong section / wrong area processed'), ('LOW_THICKNESS', 'Low thickness'), ('HIGH_THICKNESS', 'High thickness'), ('NON_UNIFORM', 'Non-uniform coverage'), ('ADHESION_FAIL', 'Adhesion failure / peel'), ('CONTAMINATION', 'Contamination / roughness / pitting'), ('BURNED_AREA', 'Burned area / overheating'), ('ETCH_DAMAGE', 'Etch or strip damage'), ('POST_TREAT_ERROR', 'Post-treatment / bake / rinse error'), ('OTHER', 'Other')], default='NONE', help_text="Observed failure mode or 'None' if acceptable.", max_length=30),
        ),
    ]
