# Generated by Django 5.2 on 2025-12-01 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0009_remove_logentry_is_accept_logentry_inspection_result_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyInspectionLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateTimeField(auto_now_add=True, verbose_name='Log Date and Time')),
                ('containment_is_clean', models.BooleanField(default=True, help_text='Is secondary containment free of waste and liquid?')),
                ('system_undamaged', models.BooleanField(default=True, help_text='Is the system free of corrosion and evident damage?')),
                ('leaks_present', models.BooleanField(default=False, help_text='Are there any leaks?', verbose_name='Leaks Present')),
                ('pipes_are_secure', models.BooleanField(default=True, help_text='Are pipes, valves, and pumps free of leaks and in good condition?')),
                ('tank_lid_closed', models.BooleanField(default=True, help_text='Is the tank lid closed?')),
                ('notes', models.TextField(blank=True, help_text='Add any notes/comments')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Recorded By')),
            ],
            options={
                'verbose_name_plural': 'Daily Inspection Log Entries',
                'ordering': ['-log_date'],
            },
        ),
    ]
