# Generated by Django 5.2 on 2025-12-01 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0010_dailyinspectionlogentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyinspectionlogentry',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='recorded by'),
        ),
        migrations.CreateModel(
            name='ScrubberLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateTimeField(auto_now_add=True, verbose_name='Log Date and Time')),
                ('stage_one_reading', models.DecimalField(blank=True, decimal_places=2, help_text='Min 0.7 inches, Max 2.7 inches', max_digits=5, null=True, verbose_name='Stage 1 Reading (in)')),
                ('stage_two_reading', models.DecimalField(blank=True, decimal_places=2, help_text='Min 0.7 inches, Max 4.7 inches', max_digits=5, null=True, verbose_name='Stage 2 Reading (in)')),
                ('stage_three_reading', models.DecimalField(blank=True, decimal_places=2, help_text='Min 0.8 inches, Max 2.8 inches', max_digits=5, null=True, verbose_name='Stage 3 Reading (in)')),
                ('limits_exceeded', models.BooleanField(default=False, help_text='Check True if any reading is outside the specified range.', verbose_name='Limits Exceeded')),
                ('notes', models.TextField(blank=True, help_text='Add any notes/comments')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Recorded By')),
            ],
            options={
                'verbose_name_plural': 'Scrubber Logs',
                'ordering': ['-log_date'],
            },
        ),
    ]
