# Generated by Django 5.2 on 2025-12-01 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0011_alter_dailyinspectionlogentry_operator_scrubberlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrubberlog',
            name='stage_one_reading',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Stage 1: Min 0.7 inches, Max 2.7 inches', max_digits=5, null=True, verbose_name='Stage 1 Reading (in)'),
        ),
        migrations.AlterField(
            model_name='scrubberlog',
            name='stage_three_reading',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Stage 3: Min 0.8 inches, Max 2.8 inches', max_digits=5, null=True, verbose_name='Stage 3 Reading (in)'),
        ),
        migrations.AlterField(
            model_name='scrubberlog',
            name='stage_two_reading',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Stage 2: Min 0.7 inches, Max 4.7 inches', max_digits=5, null=True, verbose_name='Stage 2 Reading (in)'),
        ),
    ]
