# Generated by Django 5.2 on 2025-12-01 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0012_alter_scrubberlog_stage_one_reading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrubberlog',
            name='limits_exceeded',
            field=models.BooleanField(default=False, help_text='Do values exceed limits?', verbose_name='Limits Exceeded'),
        ),
    ]
