# Generated by Django 5.2 on 2025-12-02 17:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0013_alter_scrubberlog_limits_exceeded'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyinspectionlogentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailyinspectionlogentry',
            name='log_date',
            field=models.DateTimeField(help_text='Enter the exact date and time of inspection', verbose_name='Log Date and Time'),
        ),
        migrations.AlterField(
            model_name='dailyinspectionlogentry',
            name='operator',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=100, verbose_name='recorded by'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scrubberlog',
            name='log_date',
            field=models.DateTimeField(help_text='Enter the date and time the reading was taken.', verbose_name='Log Date and Time'),
        ),
        migrations.AlterField(
            model_name='scrubberlog',
            name='operator',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=100, verbose_name='Recorded By'),
            preserve_default=False,
        ),
    ]
